In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import statsmodels as sm
from statsmodels.formula.api import ols
from statsmodels.stats.anova import anova_lm
import pingouin as pg
import sys

# Create a dictionary of versions
versions = {
    "Python": sys.version.split()[0],
    "Pandas": pd.__version__,
    "NumPy": np.__version__,
    "Matplotlib": plt.matplotlib.__version__,
    "Seaborn": sns.__version__,
    "Statsmodels": sm.__version__,
    "Pingouin": pg.__version__
}

# Display as a clean DataFrame
df_versions = pd.DataFrame(list(versions.items()), columns=['Library', 'Version'])
df_versions

       Library Version
0       Python  3.13.9
1       Pandas   2.3.3
2        NumPy   2.3.4
3   Matplotlib  3.10.7
4      Seaborn  0.13.2
5  Statsmodels  0.14.5
6     Pingouin   0.5.5

## Read Data

In [2]:
# display all columns
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)
# reset options
# pd.reset_option('display.max_columns')

In [3]:
# load using pyarrow for performance (crime data is joined between crime & neighborhood & police using geom)
df_crime = pd.read_csv("../Data/chicago_crimes_export.csv", engine="pyarrow", dtype_backend="pyarrow")
df_arrest = pd.read_csv("../Data/chicago_arrests_export.csv", engine="pyarrow", dtype_backend="pyarrow")

## Check Data

In [4]:
df_crime.describe(include='all').T

,count,unique,top,freq,mean,min,25%,50%,75%,max,std
case_number,8353122,8352516,HZ140230,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN
date,8353122,NaN,NaN,NaN,2011-07-31 14:09:03,2001-01-01 00:00:00,2005-06-14 21:30:00,2010-06-05 04:42:00,2017-05-08 09:19:15,2025-12-24 00:00:00,NaN
block,8353122,63692,001XX N STATE ST,16996,NaN,NaN,NaN,NaN,NaN,NaN,NaN
iucr,8353122,416,0820,671522,NaN,NaN,NaN,NaN,NaN,NaN,NaN
primary_type,8353122,34,THEFT,1769511,NaN,NaN,NaN,NaN,NaN,NaN,NaN
description,8353122,565,SIMPLE,988659,NaN,NaN,NaN,NaN,NaN,NaN,NaN
location_description,8343134,218,STREET,2194409,NaN,NaN,NaN,NaN,NaN,NaN,NaN
arrest,8353122,2,f,6247440,NaN,NaN,NaN,NaN,NaN,NaN,NaN
domestic,8353122,2,f,6905712,NaN,NaN,NaN,NaN,NaN,NaN,NaN
beat,8353122.0,<NA>,<NA>,<NA>,1181.414643,111.0,621.0,1034.0,1731.0,2535.0,703.134414
district,8353075.0,<NA>,<NA>,<NA>,11.275695,1.0,6.0,10.0,17.0,31.0,6.956177
ward,7748108.0,<NA>,<NA>,<NA>,22.747217,1.0,10.0,23.0,34.0,50.0,13.851733
community_area,7749183.0,<NA>,<NA>,<NA>,37.396219,0.0,23.0,32.0,56.0,77.0,21.523476
year,8353122.0,<NA>,<NA>,<NA>,2011.075313,2001.0,2005.0,2010.0,2017.0,2025.0,7.126041
updated_on,8353122,NaN,NaN,NaN,2019-03-05 09:30:13,2006-03-31 22:03:38,2018-02-10 15:50:01,2018-02-28 15:56:25,2019-02-27 16:21:40,2025-12-31 15:41:59,NaN
zip_code,8353122.0,<NA>,<NA>,<NA>,60630.337248,60601.0,60618.0,60628.0,60642.0,60827.0,20.330907
zip_code_area,8353122.0,<NA>,<NA>,<NA>,139318603.184582,4294901.86284,80526075.8505,106718949.397,176505462.842,452837420.813,92561139.105871
primary_neighborhood,8353122,98,Austin,491576,NaN,NaN,NaN,NaN,NaN,NaN,NaN
secondary_neighborhood,8353122,78,AUSTIN,491576,NaN,NaN,NaN,NaN,NaN,NaN,NaN
neighborhood_area,8353122.0,<NA>,<NA>,<NA>,90504783.766305,882405.08616,53542230.819,89130893.6364,110196097.139,371835607.687,51459204.454092
p_district,8353122.0,<NA>,<NA>,<NA>,11.274208,1.0,6.0,10.0,17.0,25.0,6.955944
p_sector,8353122.0,<NA>,<NA>,<NA>,2.02814,1.0,1.0,2.0,3.0,5.0,0.827778
p_beat,8353122.0,<NA>,<NA>,<NA>,1150.387914,111.0,612.0,1024.0,1713.0,2535.0,696.265109

In [5]:
df_crime.shape

(8353122, 23)

In [6]:
print(f'Police District (Police): {df_crime.p_district.nunique()}')
print(f'Police Sector (Police): {df_crime.p_sector.nunique()}')
print(f'Beat (Police): {df_crime.p_beat.nunique()}')

Police District (Police): 22
Police Sector (Police): 4
Beat (Police): 274

In [7]:
print(f'Police beats (Crime): {df_crime.beat.nunique()}')
print(f'Police District(Crime): {df_crime.district.nunique()}')
print(f'Ward (Crime): {df_crime.ward.nunique()}')

Police beats (Crime): 304
Police District(Crime): 24
Ward (Crime): 50

In [8]:
print(f"Beat Difference: {(df_crime.beat != df_crime.p_beat).sum():,}")
print(f"District Difference: {(df_crime.district != df_crime.p_district).sum():,}")

Beat Difference: 1,572,683
District Difference: 124,361

## Data Wrangle

In [9]:
# num of rows before 
before = df_crime.shape[0]
# remove any duplicates
df_crime = df_crime.drop_duplicates().reset_index(drop=True)
# num of rows after 
after = df_crime.shape[0]
print("Duplicate Rows Removed:", before - after)
print("Shape:", df_crime.shape)

Duplicate Rows Removed: 179
Shape: (8352943, 23)

In [10]:
# display number of unique values
for i in df_crime.columns:
    print(f"{i}: {df_crime[i].nunique():,}")

case_number: 8,352,516
date: 3,518,287
block: 63,692
iucr: 416
primary_type: 34
description: 565
location_description: 218
arrest: 2
domestic: 2
beat: 304
district: 24
ward: 50
community_area: 78
year: 25
updated_on: 5,908
zip_code: 59
zip_code_area: 59
primary_neighborhood: 98
secondary_neighborhood: 78
neighborhood_area: 98
p_district: 22
p_sector: 4
p_beat: 274

In [11]:
# aggregate data
aggregate = df_crime.groupby(['year','primary_type', 'primary_neighborhood']).size().unstack().fillna(0)
aggregate.head()

primary_neighborhood      Albany Park  Andersonville  Archer Heights  \
year primary_type
2001 ARSON                       12.0            1.0             3.0
     ASSAULT                    232.0           35.0            76.0
     BATTERY                    802.0           76.0           222.0
     BURGLARY                   245.0           59.0           119.0
     CRIM SEXUAL ASSAULT         18.0            0.0             4.0

primary_neighborhood      Armour Square  Ashburn  Auburn Gresham  Austin  \
year primary_type
2001 ARSON                          4.0      8.0            14.0    72.0
     ASSAULT                       55.0    276.0           879.0  1695.0
     BATTERY                      210.0    674.0          2796.0  5594.0
     BURGLARY                      58.0    249.0           811.0   936.0
     CRIM SEXUAL ASSAULT            3.0     12.0            51.0   136.0

primary_neighborhood      Avalon Park  Avondale  Belmont Cragin  Beverly  \
year primary_type
2001 ARSON                        3.0      18.0            27.0      1.0
     ASSAULT                    167.0     280.0           565.0    116.0
     BATTERY                    430.0     754.0          1379.0    212.0
     BURGLARY                   122.0     420.0           669.0    138.0
     CRIM SEXUAL ASSAULT          5.0      14.0            19.0      3.0

primary_neighborhood      Boystown  Bridgeport  Brighton Park  Bucktown  \
year primary_type
2001 ARSON                     1.0        20.0           15.0       4.0
     ASSAULT                  23.0       185.0          258.0     112.0
     BATTERY                  71.0       546.0          757.0     216.0
     BURGLARY                 26.0       331.0          397.0     275.0
     CRIM SEXUAL ASSAULT       0.0         5.0           10.0       9.0

primary_neighborhood      Burnside  Calumet Heights  Chatham  Chicago Lawn  \
year primary_type
2001 ARSON                     7.0              6.0     18.0          29.0
     ASSAULT                  59.0            197.0    567.0         667.0
     BATTERY                 165.0            426.0   1585.0        2155.0
     BURGLARY                 26.0            161.0    529.0         826.0
     CRIM SEXUAL ASSAULT       7.0              9.0     38.0          50.0

primary_neighborhood      Chinatown  Clearing  Douglas  Dunning  East Side  \
year primary_type
2001 ARSON                      0.0       9.0      6.0      4.0        6.0
     ASSAULT                   32.0     106.0    509.0    167.0      182.0
     BATTERY                   67.0     260.0   1765.0    419.0      466.0
     BURGLARY                  33.0     154.0    177.0    204.0      145.0
     CRIM SEXUAL ASSAULT        1.0       5.0     35.0      8.0        4.0

primary_neighborhood      East Village  Edgewater  Edison Park  Englewood  \
year primary_type
2001 ARSON                         4.0       10.0          1.0       73.0
     ASSAULT                      63.0      304.0         25.0     2159.0
     BATTERY                     162.0      865.0         66.0     7130.0
     BURGLARY                    132.0      284.0         33.0     1380.0
     CRIM SEXUAL ASSAULT           1.0       22.0          1.0      134.0

primary_neighborhood      Fuller Park  Gage Park  Galewood  Garfield Park  \
year primary_type
2001 ARSON                        2.0       12.0       1.0           29.0
     ASSAULT                    106.0      235.0      67.0          892.0
     BATTERY                    333.0      668.0     153.0         3127.0
     BURGLARY                    70.0      342.0     111.0          517.0
     CRIM SEXUAL ASSAULT          3.0        9.0       4.0           60.0

primary_neighborhood      Garfield Ridge  Gold Coast  Grand Boulevard  \
year primary_type
2001 ARSON                           7.0         0.0             10.0
     ASSAULT                       265.0        29.0            702.0
     BATTERY                       619.0       158.0           2667.0
     BURGLARY                      293.0        23.0            364.0
     CRIM SEXUAL ASSAULT            12.0         2.0             45.0

primary_neighborhood      Grand Crossing  Grant Park  Greektown  Hegewisch  \
year primary_type
2001 ARSON                          22.0         0.0        0.0        4.0
     ASSAULT                       855.0         4.0       20.0       64.0
     BATTERY                      2718.0        31.0       58.0      195.0
     BURGLARY                      568.0         3.0        7.0       54.0
     CRIM SEXUAL ASSAULT            47.0         0.0        1.0        4.0

primary_neighborhood      Hermosa  Humboldt Park  Hyde Park  Irving Park  \
year primary_type
2001 ARSON                   23.0           43.0        3.0         17.0
     ASSAULT                220.0         1375.0      170.0        273.0
     BATTERY                592.0         3977.0      424.0        990.0
     BURGLARY               218.0          861.0      165.0        389.0
     CRIM SEXUAL ASSAULT     16.0           54.0       13.0         22.0

primary_neighborhood      Jackson Park  Jefferson Park  Kenwood  Lake View  \
year primary_type
2001 ARSON                         0.0             2.0      4.0        7.0
     ASSAULT                      25.0           124.0    207.0      308.0
     BATTERY                      64.0           265.0    554.0      845.0
     BURGLARY                     29.0           131.0    132.0      612.0
     CRIM SEXUAL ASSAULT           4.0             6.0     11.0       15.0

primary_neighborhood      Lincoln Park  Lincoln Square  Little Italy, UIC  \
year primary_type
2001 ARSON                         1.0             5.0                8.0
     ASSAULT                     196.0           239.0              325.0
     BATTERY                     498.0           622.0              998.0
     BURGLARY                    369.0           264.0              204.0
     CRIM SEXUAL ASSAULT          11.0             9.0               20.0

primary_neighborhood      Little Village  Logan Square   Loop  \
year primary_type
2001 ARSON                          37.0          24.0    0.0
     ASSAULT                       521.0         706.0  377.0
     BATTERY                      1715.0        1790.0  684.0
     BURGLARY                      580.0         672.0  202.0
     CRIM SEXUAL ASSAULT            28.0          33.0   12.0

primary_neighborhood      Lower West Side  Magnificent Mile  Mckinley Park  \
year primary_type
2001 ARSON                           23.0               0.0            7.0
     ASSAULT                        456.0              49.0          133.0
     BATTERY                       1095.0              76.0          304.0
     BURGLARY                       263.0              26.0          217.0
     CRIM SEXUAL ASSAULT             12.0               0.0            4.0

primary_neighborhood      Millenium Park  Montclare  Morgan Park  \
year primary_type
2001 ARSON                           0.0        5.0          7.0
     ASSAULT                         2.0       87.0        269.0
     BATTERY                         5.0      196.0        653.0
     BURGLARY                        1.0       85.0        213.0
     CRIM SEXUAL ASSAULT             0.0        2.0          7.0

primary_neighborhood      Mount Greenwood  Museum Campus  Near South Side  \
year primary_type
2001 ARSON                            3.0            0.0              3.0
     ASSAULT                         81.0            7.0            200.0
     BATTERY                        170.0           39.0            686.0
     BURGLARY                        56.0            4.0             71.0
     CRIM SEXUAL ASSAULT              1.0            1.0             11.0

primary_neighborhood      New City  North Center  North Lawndale  North Park  \
year primary_type
2001 ARSON                    40.0           9.0            30.0         1.0
     ASSAULT                 735.0         211.0           844.0        76.0
     BATTERY                2396.0         501.0          2971.0       182.0
     BURGLARY                619.0         332.0           437.0        93.0
     CRIM SEXUAL ASSAULT      44.0           6.0            50.0         5.0

primary_neighborhood      Norwood Park  O'Hare  Oakland  Old Town  \
year primary_type
2001 ARSON                         1.0     1.0      2.0       1.0
     ASSAULT                     115.0   117.0    144.0     146.0
     BATTERY                     284.0   291.0    392.0     352.0
     BURGLARY                    138.0    44.0     50.0     128.0
     CRIM SEXUAL ASSAULT           2.0     3.0      4.0       9.0

primary_neighborhood      Portage Park  Printers Row  Pullman  River North  \
year primary_type
2001 ARSON                        11.0           0.0      2.0          7.0
     ASSAULT                     326.0          18.0    173.0        408.0
     BATTERY                     842.0          47.0    380.0       1644.0
     BURGLARY                    455.0          14.0     80.0        299.0
     CRIM SEXUAL ASSAULT          10.0           0.0     10.0         20.0

primary_neighborhood      Riverdale  Rogers Park  Roseland  Rush & Division  \
year primary_type
2001 ARSON                      4.0         13.0      37.0              0.0
     ASSAULT                  262.0        526.0    1035.0             77.0
     BATTERY                  888.0       1647.0    2922.0            261.0
     BURGLARY                 106.0        382.0     606.0             37.0
     CRIM SEXUAL ASSAULT       13.0         26.0      56.0              5.0

primary_neighborhood      Sauganash,Forest Glen  Sheffield & DePaul  \
year primary_type
2001 ARSON                                  1.0                 3.0
     ASSAULT                               35.0                37.0
     BATTERY                               85.0               118.0
     BURGLARY                              79.0                92.0
     CRIM SEXUAL ASSAULT                    4.0                 6.0

primary_neighborhood      South Chicago  South Deering  South Shore  \
year primary_type
2001 ARSON                         14.0            9.0         15.0
     ASSAULT                      720.0          216.0       1158.0
     BATTERY                     2009.0          596.0       3354.0
     BURGLARY                     359.0          136.0        776.0
     CRIM SEXUAL ASSAULT           43.0           11.0         66.0

primary_neighborhood      Streeterville  Ukrainian Village  United Center  \
year primary_type
2001 ARSON                          0.0                2.0            2.0
     ASSAULT                       70.0               79.0          318.0
     BATTERY                      187.0              235.0         1095.0
     BURGLARY                      61.0              165.0          131.0
     CRIM SEXUAL ASSAULT            3.0                4.0           13.0

primary_neighborhood      Uptown  Washington Heights  Washington Park  \
year primary_type
2001 ARSON                  13.0                 8.0             12.0
     ASSAULT               546.0               390.0            428.0
     BATTERY              1637.0               934.0           1580.0
     BURGLARY              261.0               257.0            212.0
     CRIM SEXUAL ASSAULT    28.0                16.0             40.0

primary_neighborhood      West Elsdon  West Lawn  West Loop  West Pullman  \
year primary_type
2001 ARSON                        5.0       11.0        1.0          17.0
     ASSAULT                     71.0      156.0      155.0         624.0
     BATTERY                    199.0      450.0      308.0        1753.0
     BURGLARY                   156.0      207.0      146.0         485.0
     CRIM SEXUAL ASSAULT          4.0        5.0       10.0          35.0

primary_neighborhood      West Ridge  West Town  Wicker Park  Woodlawn  \
year primary_type
2001 ARSON                       8.0       14.0          7.0      18.0
     ASSAULT                   274.0      259.0        273.0     633.0
     BATTERY                   776.0      731.0        717.0    1923.0
     BURGLARY                  334.0      395.0        440.0     329.0
     CRIM SEXUAL ASSAULT        25.0       13.0         26.0      39.0

primary_neighborhood      Wrigleyville
year primary_type
2001 ARSON                         0.0
     ASSAULT                      21.0
     BATTERY                     115.0
     BURGLARY                     47.0
     CRIM SEXUAL ASSAULT           1.0

In [12]:
list(aggregate.index)

[(2001, 'ARSON'),
 (2001, 'ASSAULT'),
 (2001, 'BATTERY'),
 (2001, 'BURGLARY'),
 (2001, 'CRIM SEXUAL ASSAULT'),
 (2001, 'CRIMINAL DAMAGE'),
 (2001, 'CRIMINAL SEXUAL ASSAULT'),
 (2001, 'CRIMINAL TRESPASS'),
 (2001, 'DECEPTIVE PRACTICE'),
 (2001, 'DOMESTIC VIOLENCE'),
 (2001, 'GAMBLING'),
 (2001, 'HOMICIDE'),
 (2001, 'INTERFERENCE WITH PUBLIC OFFICER'),
 (2001, 'INTIMIDATION'),
 (2001, 'KIDNAPPING'),
 (2001, 'LIQUOR LAW VIOLATION'),
 (2001, 'MOTOR VEHICLE THEFT'),
 (2001, 'NARCOTICS'),
 (2001, 'OBSCENITY'),
 (2001, 'OFFENSE INVOLVING CHILDREN'),
 (2001, 'OTHER NARCOTIC VIOLATION'),
 (2001, 'OTHER OFFENSE'),
 (2001, 'PROSTITUTION'),
 (2001, 'PUBLIC INDECENCY'),
 (2001, 'PUBLIC PEACE VIOLATION'),
 (2001, 'RITUALISM'),
 (2001, 'ROBBERY'),
 (2001, 'SEX OFFENSE'),
 (2001, 'STALKING'),
 (2001, 'THEFT'),
 (2001, 'WEAPONS VIOLATION'),
 (2002, 'ARSON'),
 (2002, 'ASSAULT'),
 (2002, 'BATTERY'),
 (2002, 'BURGLARY'),
 (2002, 'CRIM SEXUAL ASSAULT'),
 (2002, 'CRIMINAL DAMAGE'),
 (2002, 'CRIMINAL SEXUAL ASSAULT'),
 (2002, 'CRIMINAL TRESPASS'),
 (2002, 'DECEPTIVE PRACTICE'),
 (2002, 'GAMBLING'),
 (2002, 'HOMICIDE'),
 (2002, 'INTERFERENCE WITH PUBLIC OFFICER'),
 (2002, 'INTIMIDATION'),
 (2002, 'KIDNAPPING'),
 (2002, 'LIQUOR LAW VIOLATION'),
 (2002, 'MOTOR VEHICLE THEFT'),
 (2002, 'NARCOTICS'),
 (2002, 'OBSCENITY'),
 (2002, 'OFFENSE INVOLVING CHILDREN'),
 (2002, 'OTHER NARCOTIC VIOLATION'),
 (2002, 'OTHER OFFENSE'),
 (2002, 'PROSTITUTION'),
 (2002, 'PUBLIC INDECENCY'),
 (2002, 'PUBLIC PEACE VIOLATION'),
 (2002, 'RITUALISM'),
 (2002, 'ROBBERY'),
 (2002, 'SEX OFFENSE'),
 (2002, 'STALKING'),
 (2002, 'THEFT'),
 (2002, 'WEAPONS VIOLATION'),
 (2003, 'ARSON'),
 (2003, 'ASSAULT'),
 (2003, 'BATTERY'),
 (2003, 'BURGLARY'),
 (2003, 'CRIM SEXUAL ASSAULT'),
 (2003, 'CRIMINAL DAMAGE'),
 (2003, 'CRIMINAL SEXUAL ASSAULT'),
 (2003, 'CRIMINAL TRESPASS'),
 (2003, 'DECEPTIVE PRACTICE'),
 (2003, 'GAMBLING'),
 (2003, 'HOMICIDE'),
 (2003, 'INTERFERENCE WITH PUBLIC OFFICER'),
 (2003, 'INTIMIDATION'),
 (2003, 'KIDNAPPING'),
 (2003, 'LIQUOR LAW VIOLATION'),
 (2003, 'MOTOR VEHICLE THEFT'),
 (2003, 'NARCOTICS'),
 (2003, 'OBSCENITY'),
 (2003, 'OFFENSE INVOLVING CHILDREN'),
 (2003, 'OTHER NARCOTIC VIOLATION'),
 (2003, 'OTHER OFFENSE'),
 (2003, 'PROSTITUTION'),
 (2003, 'PUBLIC INDECENCY'),
 (2003, 'PUBLIC PEACE VIOLATION'),
 (2003, 'RITUALISM'),
 (2003, 'ROBBERY'),
 (2003, 'SEX OFFENSE'),
 (2003, 'STALKING'),
 (2003, 'THEFT'),
 (2003, 'WEAPONS VIOLATION'),
 (2004, 'ARSON'),
 (2004, 'ASSAULT'),
 (2004, 'BATTERY'),
 (2004, 'BURGLARY'),
 (2004, 'CRIM SEXUAL ASSAULT'),
 (2004, 'CRIMINAL DAMAGE'),
 (2004, 'CRIMINAL SEXUAL ASSAULT'),
 (2004, 'CRIMINAL TRESPASS'),
 (2004, 'DECEPTIVE PRACTICE'),
 (2004, 'GAMBLING'),
 (2004, 'HOMICIDE'),
 (2004, 'INTERFERENCE WITH PUBLIC OFFICER'),
 (2004, 'INTIMIDATION'),
 (2004, 'KIDNAPPING'),
 (2004, 'LIQUOR LAW VIOLATION'),
 (2004, 'MOTOR VEHICLE THEFT'),
 (2004, 'NARCOTICS'),
 (2004, 'OBSCENITY'),
 (2004, 'OFFENSE INVOLVING CHILDREN'),
 (2004, 'OTHER NARCOTIC VIOLATION'),
 (2004, 'OTHER OFFENSE'),
 (2004, 'PROSTITUTION'),
 (2004, 'PUBLIC INDECENCY'),
 (2004, 'PUBLIC PEACE VIOLATION'),
 (2004, 'RITUALISM'),
 (2004, 'ROBBERY'),
 (2004, 'SEX OFFENSE'),
 (2004, 'STALKING'),
 (2004, 'THEFT'),
 (2004, 'WEAPONS VIOLATION'),
 (2005, 'ARSON'),
 (2005, 'ASSAULT'),
 (2005, 'BATTERY'),
 (2005, 'BURGLARY'),
 (2005, 'CRIM SEXUAL ASSAULT'),
 (2005, 'CRIMINAL DAMAGE'),
 (2005, 'CRIMINAL SEXUAL ASSAULT'),
 (2005, 'CRIMINAL TRESPASS'),
 (2005, 'DECEPTIVE PRACTICE'),
 (2005, 'GAMBLING'),
 (2005, 'HOMICIDE'),
 (2005, 'INTERFERENCE WITH PUBLIC OFFICER'),
 (2005, 'INTIMIDATION'),
 (2005, 'KIDNAPPING'),
 (2005, 'LIQUOR LAW VIOLATION'),
 (2005, 'MOTOR VEHICLE THEFT'),
 (2005, 'NARCOTICS'),
 (2005, 'OBSCENITY'),
 (2005, 'OFFENSE INVOLVING CHILDREN'),
 (2005, 'OTHER NARCOTIC VIOLATION'),
 (2005, 'OTHER OFFENSE'),
 (2005, 'PROSTITUTION'),
 (2005, 'PUBLIC INDECENCY'),
 (2005, 'PUBLIC PEACE VIOLATION'),
 (2005, 'RITUALISM'),
 (2005, 'ROBBERY'),
 (2005, 'SEX OFFENSE'),
 (2005, 'STALKING'),
 (2005, 'THEFT'),
 (2005, 'WEAPONS VIOLATION'),
 (2006, 'ARSON'),
 (2006, 'ASSAULT'),
 (2006, 'BATTERY'),
 (2006, 'BURGLARY'),
 (2006, 'CRIM SEXUAL ASSAULT'),
 (2006, 'CRIMINAL DAMAGE'),
 (2006, 'CRIMINAL SEXUAL ASSAULT'),
 (2006, 'CRIMINAL TRESPASS'),
 (2006, 'DECEPTIVE PRACTICE'),
 (2006, 'GAMBLING'),
 (2006, 'HOMICIDE'),
 (2006, 'INTERFERENCE WITH PUBLIC OFFICER'),
 (2006, 'INTIMIDATION'),
 (2006, 'KIDNAPPING'),
 (2006, 'LIQUOR LAW VIOLATION'),
 (2006, 'MOTOR VEHICLE THEFT'),
 (2006, 'NARCOTICS'),
 (2006, 'OBSCENITY'),
 (2006, 'OFFENSE INVOLVING CHILDREN'),
 (2006, 'OTHER NARCOTIC VIOLATION'),
 (2006, 'OTHER OFFENSE'),
 (2006, 'PROSTITUTION'),
 (2006, 'PUBLIC INDECENCY'),
 (2006, 'PUBLIC PEACE VIOLATION'),
 (2006, 'RITUALISM'),
 (2006, 'ROBBERY'),
 (2006, 'SEX OFFENSE'),
 (2006, 'STALKING'),
 (2006, 'THEFT'),
 (2006, 'WEAPONS VIOLATION'),
 (2007, 'ARSON'),
 (2007, 'ASSAULT'),
 (2007, 'BATTERY'),
 (2007, 'BURGLARY'),
 (2007, 'CRIM SEXUAL ASSAULT'),
 (2007, 'CRIMINAL DAMAGE'),
 (2007, 'CRIMINAL SEXUAL ASSAULT'),
 (2007, 'CRIMINAL TRESPASS'),
 (2007, 'DECEPTIVE PRACTICE'),
 (2007, 'GAMBLING'),
 (2007, 'HOMICIDE'),
 (2007, 'INTERFERENCE WITH PUBLIC OFFICER'),
 (2007, 'INTIMIDATION'),
 (2007, 'KIDNAPPING'),
 (2007, 'LIQUOR LAW VIOLATION'),
 (2007, 'MOTOR VEHICLE THEFT'),
 (2007, 'NARCOTICS'),
 (2007, 'OBSCENITY'),
 (2007, 'OFFENSE INVOLVING CHILDREN'),
 (2007, 'OTHER NARCOTIC VIOLATION'),
 (2007, 'OTHER OFFENSE'),
 (2007, 'PROSTITUTION'),
 (2007, 'PUBLIC INDECENCY'),
 (2007, 'PUBLIC PEACE VIOLATION'),
 (2007, 'RITUALISM'),
 (2007, 'ROBBERY'),
 (2007, 'SEX OFFENSE'),
 (2007, 'STALKING'),
 (2007, 'THEFT'),
 (2007, 'WEAPONS VIOLATION'),
 (2008, 'ARSON'),
 (2008, 'ASSAULT'),
 (2008, 'BATTERY'),
 (2008, 'BURGLARY'),
 (2008, 'CRIM SEXUAL ASSAULT'),
 (2008, 'CRIMINAL DAMAGE'),
 (2008, 'CRIMINAL SEXUAL ASSAULT'),
 (2008, 'CRIMINAL TRESPASS'),
 (2008, 'DECEPTIVE PRACTICE'),
 (2008, 'GAMBLING'),
 (2008, 'HOMICIDE'),
 (2008, 'INTERFERENCE WITH PUBLIC OFFICER'),
 (2008, 'INTIMIDATION'),
 (2008, 'KIDNAPPING'),
 (2008, 'LIQUOR LAW VIOLATION'),
 (2008, 'MOTOR VEHICLE THEFT'),
 (2008, 'NARCOTICS'),
 (2008, 'OBSCENITY'),
 (2008, 'OFFENSE INVOLVING CHILDREN'),
 (2008, 'OTHER NARCOTIC VIOLATION'),
 (2008, 'OTHER OFFENSE'),
 (2008, 'PROSTITUTION'),
 (2008, 'PUBLIC INDECENCY'),
 (2008, 'PUBLIC PEACE VIOLATION'),
 (2008, 'ROBBERY'),
 (2008, 'SEX OFFENSE'),
 (2008, 'STALKING'),
 (2008, 'THEFT'),
 (2008, 'WEAPONS VIOLATION'),
 (2009, 'ARSON'),
 (2009, 'ASSAULT'),
 (2009, 'BATTERY'),
 (2009, 'BURGLARY'),
 (2009, 'CRIM SEXUAL ASSAULT'),
 (2009, 'CRIMINAL DAMAGE'),
 (2009, 'CRIMINAL SEXUAL ASSAULT'),
 (2009, 'CRIMINAL TRESPASS'),
 (2009, 'DECEPTIVE PRACTICE'),
 (2009, 'GAMBLING'),
 (2009, 'HOMICIDE'),
 (2009, 'INTERFERENCE WITH PUBLIC OFFICER'),
 (2009, 'INTIMIDATION'),
 (2009, 'KIDNAPPING'),
 (2009, 'LIQUOR LAW VIOLATION'),
 (2009, 'MOTOR VEHICLE THEFT'),
 (2009, 'NARCOTICS'),
 (2009, 'OBSCENITY'),
 (2009, 'OFFENSE INVOLVING CHILDREN'),
 (2009, 'OTHER NARCOTIC VIOLATION'),
 (2009, 'OTHER OFFENSE'),
 (2009, 'PROSTITUTION'),
 (2009, 'PUBLIC INDECENCY'),
 (2009, 'PUBLIC PEACE VIOLATION'),
 (2009, 'ROBBERY'),
 (2009, 'SEX OFFENSE'),
 (2009, 'STALKING'),
 (2009, 'THEFT'),
 (2009, 'WEAPONS VIOLATION'),
 (2010, 'ARSON'),
 (2010, 'ASSAULT'),
 (2010, 'BATTERY'),
 (2010, 'BURGLARY'),
 (2010, 'CRIM SEXUAL ASSAULT'),
 (2010, 'CRIMINAL DAMAGE'),
 (2010, 'CRIMINAL SEXUAL ASSAULT'),
 (2010, 'CRIMINAL TRESPASS'),
 (2010, 'DECEPTIVE PRACTICE'),
 (2010, 'GAMBLING'),
 (2010, 'HOMICIDE'),
 (2010, 'INTERFERENCE WITH PUBLIC OFFICER'),
 (2010, 'INTIMIDATION'),
 (2010, 'KIDNAPPING'),
 (2010, 'LIQUOR LAW VIOLATION'),
 (2010, 'MOTOR VEHICLE THEFT'),
 (2010, 'NARCOTICS'),
 (2010, 'OBSCENITY'),
 (2010, 'OFFENSE INVOLVING CHILDREN'),
 (2010, 'OTHER NARCOTIC VIOLATION'),
 (2010, 'OTHER OFFENSE'),
 (2010, 'PROSTITUTION'),
 (2010, 'PUBLIC INDECENCY'),
 (2010, 'PUBLIC PEACE VIOLATION'),
 (2010, 'ROBBERY'),
 (2010, 'SEX OFFENSE'),
 (2010, 'STALKING'),
 (2010, 'THEFT'),
 (2010, 'WEAPONS VIOLATION'),
 (2011, 'ARSON'),
 (2011, 'ASSAULT'),
 (2011, 'BATTERY'),
 (2011, 'BURGLARY'),
 (2011, 'CRIM SEXUAL ASSAULT'),
 (2011, 'CRIMINAL DAMAGE'),
 (2011, 'CRIMINAL SEXUAL ASSAULT'),
 (2011, 'CRIMINAL TRESPASS'),
 (2011, 'DECEPTIVE PRACTICE'),
 (2011, 'GAMBLING'),
 (2011, 'HOMICIDE'),
 (2011, 'INTERFERENCE WITH PUBLIC OFFICER'),
 (2011, 'INTIMIDATION'),
 (2011, 'KIDNAPPING'),
 (2011, 'LIQUOR LAW VIOLATION'),
 (2011, 'MOTOR VEHICLE THEFT'),
 (2011, 'NARCOTICS'),
 (2011, 'OBSCENITY'),
 (2011, 'OFFENSE INVOLVING CHILDREN'),
 (2011, 'OTHER NARCOTIC VIOLATION'),
 (2011, 'OTHER OFFENSE'),
 (2011, 'PROSTITUTION'),
 (2011, 'PUBLIC INDECENCY'),
 (2011, 'PUBLIC PEACE VIOLATION'),
 (2011, 'ROBBERY'),
 (2011, 'SEX OFFENSE'),
 (2011, 'STALKING'),
 (2011, 'THEFT'),
 (2011, 'WEAPONS VIOLATION'),
 (2012, 'ARSON'),
 (2012, 'ASSAULT'),
 (2012, 'BATTERY'),
 (2012, 'BURGLARY'),
 (2012, 'CRIM SEXUAL ASSAULT'),
 (2012, 'CRIMINAL DAMAGE'),
 (2012, 'CRIMINAL SEXUAL ASSAULT'),
 (2012, 'CRIMINAL TRESPASS'),
 (2012, 'DECEPTIVE PRACTICE'),
 (2012, 'GAMBLING'),
 (2012, 'HOMICIDE'),
 (2012, 'INTERFERENCE WITH PUBLIC OFFICER'),
 (2012, 'INTIMIDATION'),
 (2012, 'KIDNAPPING'),
 (2012, 'LIQUOR LAW VIOLATION'),
 (2012, 'MOTOR VEHICLE THEFT'),
 (2012, 'NARCOTICS'),
 (2012, 'OBSCENITY'),
 (2012, 'OFFENSE INVOLVING CHILDREN'),
 (2012, 'OTHER NARCOTIC VIOLATION'),
 (2012, 'OTHER OFFENSE'),
 (2012, 'PROSTITUTION'),
 (2012, 'PUBLIC INDECENCY'),
 (2012, 'PUBLIC PEACE VIOLATION'),
 (2012, 'ROBBERY'),
 (2012, 'SEX OFFENSE'),
 (2012, 'STALKING'),
 (2012, 'THEFT'),
 (2012, 'WEAPONS VIOLATION'),
 (2013, 'ARSON'),
 (2013, 'ASSAULT'),
 (2013, 'BATTERY'),
 (2013, 'BURGLARY'),
 (2013, 'CRIM SEXUAL ASSAULT'),
 (2013, 'CRIMINAL DAMAGE'),
 (2013, 'CRIMINAL SEXUAL ASSAULT'),
 (2013, 'CRIMINAL TRESPASS'),
 (2013, 'DECEPTIVE PRACTICE'),
 (2013, 'GAMBLING'),
 (2013, 'HOMICIDE'),
 (2013, 'HUMAN TRAFFICKING'),
 (2013, 'INTERFERENCE WITH PUBLIC OFFICER'),
 (2013, 'INTIMIDATION'),
 (2013, 'KIDNAPPING'),
 (2013, 'LIQUOR LAW VIOLATION'),
 (2013, 'MOTOR VEHICLE THEFT'),
 (2013, 'NARCOTICS'),
 (2013, 'OBSCENITY'),
 (2013, 'OFFENSE INVOLVING CHILDREN'),
 (2013, 'OTHER NARCOTIC VIOLATION'),
 (2013, 'OTHER OFFENSE'),
 (2013, 'PROSTITUTION'),
 (2013, 'PUBLIC INDECENCY'),
 (2013, 'PUBLIC PEACE VIOLATION'),
 (2013, 'ROBBERY'),
 (2013, 'SEX OFFENSE'),
 (2013, 'STALKING'),
 (2013, 'THEFT'),
 (2013, 'WEAPONS VIOLATION'),
 (2014, 'ARSON'),
 (2014, 'ASSAULT'),
 (2014, 'BATTERY'),
 (2014, 'BURGLARY'),
 (2014, 'CONCEALED CARRY LICENSE VIOLATION'),
 (2014, 'CRIM SEXUAL ASSAULT'),
 (2014, 'CRIMINAL DAMAGE'),
 (2014, 'CRIMINAL SEXUAL ASSAULT'),
 (2014, 'CRIMINAL TRESPASS'),
 (2014, 'DECEPTIVE PRACTICE'),
 (2014, 'GAMBLING'),
 (2014, 'HOMICIDE'),
 (2014, 'HUMAN TRAFFICKING'),
 (2014, 'INTERFERENCE WITH PUBLIC OFFICER'),
 (2014, 'INTIMIDATION'),
 (2014, 'KIDNAPPING'),
 (2014, 'LIQUOR LAW VIOLATION'),
 (2014, 'MOTOR VEHICLE THEFT'),
 (2014, 'NARCOTICS'),
 (2014, 'OBSCENITY'),
 (2014, 'OFFENSE INVOLVING CHILDREN'),
 (2014, 'OTHER NARCOTIC VIOLATION'),
 (2014, 'OTHER OFFENSE'),
 (2014, 'PROSTITUTION'),
 (2014, 'PUBLIC INDECENCY'),
 (2014, 'PUBLIC PEACE VIOLATION'),
 (2014, 'ROBBERY'),
 (2014, 'SEX OFFENSE'),
 (2014, 'STALKING'),
 (2014, 'THEFT'),
 (2014, 'WEAPONS VIOLATION'),
 (2015, 'ARSON'),
 (2015, 'ASSAULT'),
 (2015, 'BATTERY'),
 (2015, 'BURGLARY'),
 (2015, 'CONCEALED CARRY LICENSE VIOLATION'),
 (2015, 'CRIM SEXUAL ASSAULT'),
 (2015, 'CRIMINAL DAMAGE'),
 (2015, 'CRIMINAL SEXUAL ASSAULT'),
 (2015, 'CRIMINAL TRESPASS'),
 (2015, 'DECEPTIVE PRACTICE'),
 (2015, 'GAMBLING'),
 (2015, 'HOMICIDE'),
 (2015, 'HUMAN TRAFFICKING'),
 (2015, 'INTERFERENCE WITH PUBLIC OFFICER'),
 (2015, 'INTIMIDATION'),
 (2015, 'KIDNAPPING'),
 (2015, 'LIQUOR LAW VIOLATION'),
 (2015, 'MOTOR VEHICLE THEFT'),
 (2015, 'NARCOTICS'),
 (2015, 'NON-CRIMINAL'),
 (2015, 'OBSCENITY'),
 (2015, 'OFFENSE INVOLVING CHILDREN'),
 (2015, 'OTHER NARCOTIC VIOLATION'),
 (2015, 'OTHER OFFENSE'),
 (2015, 'PROSTITUTION'),
 (2015, 'PUBLIC INDECENCY'),
 (2015, 'PUBLIC PEACE VIOLATION'),
 (2015, 'ROBBERY'),
 (2015, 'SEX OFFENSE'),
 (2015, 'STALKING'),
 (2015, 'THEFT'),
 (2015, 'WEAPONS VIOLATION'),
 (2016, 'ARSON'),
 (2016, 'ASSAULT'),
 (2016, 'BATTERY'),
 (2016, 'BURGLARY'),
 (2016, 'CONCEALED CARRY LICENSE VIOLATION'),
 (2016, 'CRIM SEXUAL ASSAULT'),
 (2016, 'CRIMINAL DAMAGE'),
 (2016, 'CRIMINAL SEXUAL ASSAULT'),
 (2016, 'CRIMINAL TRESPASS'),
 (2016, 'DECEPTIVE PRACTICE'),
 (2016, 'GAMBLING'),
 (2016, 'HOMICIDE'),
 (2016, 'HUMAN TRAFFICKING'),
 (2016, 'INTERFERENCE WITH PUBLIC OFFICER'),
 (2016, 'INTIMIDATION'),
 (2016, 'KIDNAPPING'),
 (2016, 'LIQUOR LAW VIOLATION'),
 (2016, 'MOTOR VEHICLE THEFT'),
 (2016, 'NARCOTICS'),
 (2016, 'NON-CRIMINAL'),
 (2016, 'OBSCENITY'),
 (2016, 'OFFENSE INVOLVING CHILDREN'),
 (2016, 'OTHER NARCOTIC VIOLATION'),
 (2016, 'OTHER OFFENSE'),
 (2016, 'PROSTITUTION'),
 (2016, 'PUBLIC INDECENCY'),
 (2016, 'PUBLIC PEACE VIOLATION'),
 (2016, 'ROBBERY'),
 (2016, 'SEX OFFENSE'),
 (2016, 'STALKING'),
 (2016, 'THEFT'),
 (2016, 'WEAPONS VIOLATION'),
 (2017, 'ARSON'),
 (2017, 'ASSAULT'),
 (2017, 'BATTERY'),
 (2017, 'BURGLARY'),
 (2017, 'CONCEALED CARRY LICENSE VIOLATION'),
 (2017, 'CRIM SEXUAL ASSAULT'),
 (2017, 'CRIMINAL DAMAGE'),
 (2017, 'CRIMINAL SEXUAL ASSAULT'),
 (2017, 'CRIMINAL TRESPASS'),
 (2017, 'DECEPTIVE PRACTICE'),
 (2017, 'GAMBLING'),
 (2017, 'HOMICIDE'),
 (2017, 'HUMAN TRAFFICKING'),
 (2017, 'INTERFERENCE WITH PUBLIC OFFICER'),
 (2017, 'INTIMIDATION'),
 (2017, 'KIDNAPPING'),
 (2017, 'LIQUOR LAW VIOLATION'),
 (2017, 'MOTOR VEHICLE THEFT'),
 (2017, 'NARCOTICS'),
 (2017, 'NON-CRIMINAL'),
 (2017, 'OBSCENITY'),
 (2017, 'OFFENSE INVOLVING CHILDREN'),
 (2017, 'OTHER NARCOTIC VIOLATION'),
 (2017, 'OTHER OFFENSE'),
 (2017, 'PROSTITUTION'),
 (2017, 'PUBLIC INDECENCY'),
 (2017, 'PUBLIC PEACE VIOLATION'),
 (2017, 'ROBBERY'),
 (2017, 'SEX OFFENSE'),
 (2017, 'STALKING'),
 (2017, 'THEFT'),
 (2017, 'WEAPONS VIOLATION'),
 (2018, 'ARSON'),
 (2018, 'ASSAULT'),
 (2018, 'BATTERY'),
 (2018, 'BURGLARY'),
 (2018, 'CONCEALED CARRY LICENSE VIOLATION'),
 (2018, 'CRIM SEXUAL ASSAULT'),
 (2018, 'CRIMINAL DAMAGE'),
 (2018, 'CRIMINAL SEXUAL ASSAULT'),
 (2018, 'CRIMINAL TRESPASS'),
 (2018, 'DECEPTIVE PRACTICE'),
 (2018, 'GAMBLING'),
 (2018, 'HOMICIDE'),
 (2018, 'HUMAN TRAFFICKING'),
 (2018, 'INTERFERENCE WITH PUBLIC OFFICER'),
 (2018, 'INTIMIDATION'),
 (2018, 'KIDNAPPING'),
 (2018, 'LIQUOR LAW VIOLATION'),
 (2018, 'MOTOR VEHICLE THEFT'),
 (2018, 'NARCOTICS'),
 (2018, 'NON-CRIMINAL'),
 (2018, 'OBSCENITY'),
 (2018, 'OFFENSE INVOLVING CHILDREN'),
 (2018, 'OTHER NARCOTIC VIOLATION'),
 (2018, 'OTHER OFFENSE'),
 (2018, 'PROSTITUTION'),
 (2018, 'PUBLIC INDECENCY'),
 (2018, 'PUBLIC PEACE VIOLATION'),
 (2018, 'ROBBERY'),
 (2018, 'SEX OFFENSE'),
 (2018, 'STALKING'),
 (2018, 'THEFT'),
 (2018, 'WEAPONS VIOLATION'),
 (2019, 'ARSON'),
 (2019, 'ASSAULT'),
 (2019, 'BATTERY'),
 (2019, 'BURGLARY'),
 (2019, 'CONCEALED CARRY LICENSE VIOLATION'),
 (2019, 'CRIM SEXUAL ASSAULT'),
 (2019, 'CRIMINAL DAMAGE'),
 (2019, 'CRIMINAL SEXUAL ASSAULT'),
 (2019, 'CRIMINAL TRESPASS'),
 (2019, 'DECEPTIVE PRACTICE'),
 (2019, 'GAMBLING'),
 (2019, 'HOMICIDE'),
 (2019, 'HUMAN TRAFFICKING'),
 (2019, 'INTERFERENCE WITH PUBLIC OFFICER'),
 (2019, 'INTIMIDATION'),
 (2019, 'KIDNAPPING'),
 (2019, 'LIQUOR LAW VIOLATION'),
 (2019, 'MOTOR VEHICLE THEFT'),
 (2019, 'NARCOTICS'),
 (2019, 'NON-CRIMINAL'),
 (2019, 'OBSCENITY'),
 (2019, 'OFFENSE INVOLVING CHILDREN'),
 (2019, 'OTHER NARCOTIC VIOLATION'),
 (2019, 'OTHER OFFENSE'),
 (2019, 'PROSTITUTION'),
 (2019, 'PUBLIC INDECENCY'),
 (2019, 'PUBLIC PEACE VIOLATION'),
 (2019, 'ROBBERY'),
 (2019, 'SEX OFFENSE'),
 (2019, 'STALKING'),
 (2019, 'THEFT'),
 (2019, 'WEAPONS VIOLATION'),
 (2020, 'ARSON'),
 (2020, 'ASSAULT'),
 (2020, 'BATTERY'),
 (2020, 'BURGLARY'),
 (2020, 'CONCEALED CARRY LICENSE VIOLATION'),
 (2020, 'CRIM SEXUAL ASSAULT'),
 (2020, 'CRIMINAL DAMAGE'),
 (2020, 'CRIMINAL SEXUAL ASSAULT'),
 (2020, 'CRIMINAL TRESPASS'),
 (2020, 'DECEPTIVE PRACTICE'),
 (2020, 'GAMBLING'),
 (2020, 'HOMICIDE'),
 (2020, 'HUMAN TRAFFICKING'),
 (2020, 'INTERFERENCE WITH PUBLIC OFFICER'),
 (2020, 'INTIMIDATION'),
 (2020, 'KIDNAPPING'),
 (2020, 'LIQUOR LAW VIOLATION'),
 (2020, 'MOTOR VEHICLE THEFT'),
 (2020, 'NARCOTICS'),
 (2020, 'NON-CRIMINAL'),
 (2020, 'OBSCENITY'),
 (2020, 'OFFENSE INVOLVING CHILDREN'),
 (2020, 'OTHER NARCOTIC VIOLATION'),
 (2020, 'OTHER OFFENSE'),
 (2020, 'PROSTITUTION'),
 (2020, 'PUBLIC INDECENCY'),
 (2020, 'PUBLIC PEACE VIOLATION'),
 (2020, 'RITUALISM'),
 (2020, 'ROBBERY'),
 (2020, 'SEX OFFENSE'),
 (2020, 'STALKING'),
 (2020, 'THEFT'),
 (2020, 'WEAPONS VIOLATION'),
 (2021, 'ARSON'),
 (2021, 'ASSAULT'),
 (2021, 'BATTERY'),
 (2021, 'BURGLARY'),
 (2021, 'CONCEALED CARRY LICENSE VIOLATION'),
 (2021, 'CRIMINAL DAMAGE'),
 (2021, 'CRIMINAL SEXUAL ASSAULT'),
 (2021, 'CRIMINAL TRESPASS'),
 (2021, 'DECEPTIVE PRACTICE'),
 (2021, 'GAMBLING'),
 (2021, 'HOMICIDE'),
 (2021, 'HUMAN TRAFFICKING'),
 (2021, 'INTERFERENCE WITH PUBLIC OFFICER'),
 (2021, 'INTIMIDATION'),
 (2021, 'KIDNAPPING'),
 (2021, 'LIQUOR LAW VIOLATION'),
 (2021, 'MOTOR VEHICLE THEFT'),
 (2021, 'NARCOTICS'),
 (2021, 'NON-CRIMINAL'),
 (2021, 'OBSCENITY'),
 (2021, 'OFFENSE INVOLVING CHILDREN'),
 (2021, 'OTHER NARCOTIC VIOLATION'),
 (2021, 'OTHER OFFENSE'),
 (2021, 'PROSTITUTION'),
 (2021, 'PUBLIC INDECENCY'),
 (2021, 'PUBLIC PEACE VIOLATION'),
 (2021, 'ROBBERY'),
 (2021, 'SEX OFFENSE'),
 (2021, 'STALKING'),
 (2021, 'THEFT'),
 (2021, 'WEAPONS VIOLATION'),
 (2022, 'ARSON'),
 (2022, 'ASSAULT'),
 (2022, 'BATTERY'),
 (2022, 'BURGLARY'),
 (2022, 'CONCEALED CARRY LICENSE VIOLATION'),
 (2022, 'CRIMINAL DAMAGE'),
 (2022, 'CRIMINAL SEXUAL ASSAULT'),
 (2022, 'CRIMINAL TRESPASS'),
 (2022, 'DECEPTIVE PRACTICE'),
 (2022, 'GAMBLING'),
 (2022, 'HOMICIDE'),
 (2022, 'HUMAN TRAFFICKING'),
 (2022, 'INTERFERENCE WITH PUBLIC OFFICER'),
 (2022, 'INTIMIDATION'),
 (2022, 'KIDNAPPING'),
 (2022, 'LIQUOR LAW VIOLATION'),
 (2022, 'MOTOR VEHICLE THEFT'),
 (2022, 'NARCOTICS'),
 (2022, 'NON-CRIMINAL'),
 (2022, 'OBSCENITY'),
 (2022, 'OFFENSE INVOLVING CHILDREN'),
 (2022, 'OTHER NARCOTIC VIOLATION'),
 (2022, 'OTHER OFFENSE'),
 (2022, 'PROSTITUTION'),
 (2022, 'PUBLIC INDECENCY'),
 (2022, 'PUBLIC PEACE VIOLATION'),
 (2022, 'ROBBERY'),
 (2022, 'SEX OFFENSE'),
 (2022, 'STALKING'),
 (2022, 'THEFT'),
 (2022, 'WEAPONS VIOLATION'),
 (2023, 'ARSON'),
 (2023, 'ASSAULT'),
 (2023, 'BATTERY'),
 (2023, 'BURGLARY'),
 (2023, 'CONCEALED CARRY LICENSE VIOLATION'),
 (2023, 'CRIMINAL DAMAGE'),
 (2023, 'CRIMINAL SEXUAL ASSAULT'),
 (2023, 'CRIMINAL TRESPASS'),
 (2023, 'DECEPTIVE PRACTICE'),
 (2023, 'GAMBLING'),
 (2023, 'HOMICIDE'),
 (2023, 'HUMAN TRAFFICKING'),
 (2023, 'INTERFERENCE WITH PUBLIC OFFICER'),
 (2023, 'INTIMIDATION'),
 (2023, 'KIDNAPPING'),
 (2023, 'LIQUOR LAW VIOLATION'),
 (2023, 'MOTOR VEHICLE THEFT'),
 (2023, 'NARCOTICS'),
 (2023, 'NON-CRIMINAL'),
 (2023, 'OBSCENITY'),
 (2023, 'OFFENSE INVOLVING CHILDREN'),
 (2023, 'OTHER NARCOTIC VIOLATION'),
 (2023, 'OTHER OFFENSE'),
 (2023, 'PROSTITUTION'),
 (2023, 'PUBLIC INDECENCY'),
 (2023, 'PUBLIC PEACE VIOLATION'),
 (2023, 'ROBBERY'),
 (2023, 'SEX OFFENSE'),
 (2023, 'STALKING'),
 (2023, 'THEFT'),
 (2023, 'WEAPONS VIOLATION'),
 (2024, 'ARSON'),
 (2024, 'ASSAULT'),
 (2024, 'BATTERY'),
 (2024, 'BURGLARY'),
 (2024, 'CONCEALED CARRY LICENSE VIOLATION'),
 (2024, 'CRIMINAL DAMAGE'),
 (2024, 'CRIMINAL SEXUAL ASSAULT'),
 (2024, 'CRIMINAL TRESPASS'),
 (2024, 'DECEPTIVE PRACTICE'),
 (2024, 'GAMBLING'),
 (2024, 'HOMICIDE'),
 (2024, 'HUMAN TRAFFICKING'),
 (2024, 'INTERFERENCE WITH PUBLIC OFFICER'),
 (2024, 'INTIMIDATION'),
 (2024, 'KIDNAPPING'),
 (2024, 'LIQUOR LAW VIOLATION'),
 (2024, 'MOTOR VEHICLE THEFT'),
 (2024, 'NARCOTICS'),
 (2024, 'NON-CRIMINAL'),
 (2024, 'OBSCENITY'),
 (2024, 'OFFENSE INVOLVING CHILDREN'),
 (2024, 'OTHER NARCOTIC VIOLATION'),
 (2024, 'OTHER OFFENSE'),
 (2024, 'PROSTITUTION'),
 (2024, 'PUBLIC INDECENCY'),
 (2024, 'PUBLIC PEACE VIOLATION'),
 (2024, 'ROBBERY'),
 (2024, 'SEX OFFENSE'),
 (2024, 'STALKING'),
 (2024, 'THEFT'),

In [13]:
aggregate.loc[2025]

primary_neighborhood,Albany Park,Andersonville,Archer Heights,Armour Square,Ashburn,Auburn Gresham,Austin,Avalon Park,Avondale,Belmont Cragin,Beverly,Boystown,Bridgeport,Brighton Park,Bucktown,Burnside,Calumet Heights,Chatham,Chicago Lawn,Chinatown,Clearing,Douglas,Dunning,East Side,East Village,Edgewater,Edison Park,Englewood,Fuller Park,Gage Park,Galewood,Garfield Park,Garfield Ridge,Gold Coast,Grand Boulevard,Grand Crossing,Grant Park,Greektown,Hegewisch,Hermosa,Humboldt Park,Hyde Park,Irving Park,Jackson Park,Jefferson Park,Kenwood,Lake View,Lincoln Park,Lincoln Square,"Little Italy, UIC",Little Village,Logan Square,Loop,Lower West Side,Magnificent Mile,Mckinley Park,Millenium Park,Montclare,Morgan Park,Mount Greenwood,Museum Campus,Near South Side,New City,North Center,North Lawndale,North Park,Norwood Park,O'Hare,Oakland,Old Town,Portage Park,Printers Row,Pullman,River North,Riverdale,Rogers Park,Roseland,Rush & Division,"Sauganash,Forest Glen",Sheffield & DePaul,South Chicago,South Deering,South Shore,Streeterville,Ukrainian Village,United Center,Uptown,Washington Heights,Washington Park,West Elsdon,West Lawn,West Loop,West Pullman,West Ridge,West Town,Wicker Park,Woodlawn,Wrigleyville
primary_type,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
ARSON,2.0,0.0,0.0,0.0,4.0,14.0,30.0,3.0,3.0,2.0,1.0,0.0,2.0,3.0,0.0,1.0,3.0,9.0,15.0,0.0,2.0,1.0,4.0,2.0,0.0,4.0,1.0,20.0,2.0,5.0,1.0,8.0,5.0,0.0,2.0,16.0,1.0,0.0,1.0,6.0,11.0,0.0,2.0,0.0,0.0,5.0,1.0,0.0,2.0,2.0,6.0,5.0,11.0,4.0,0.0,3.0,0.0,1.0,1.0,0.0,1.0,0.0,12.0,1.0,11.0,0.0,2.0,0.0,0.0,1.0,4.0,1.0,1.0,3.0,5.0,6.0,8.0,0.0,0.0,1.0,12.0,3.0,14.0,0.0,0.0,2.0,5.0,1.0,4.0,5.0,2.0,6.0,15.0,2.0,3.0,3.0,5.0,0.0
ASSAULT,203.0,26.0,72.0,71.0,205.0,674.0,1102.0,110.0,135.0,357.0,73.0,24.0,184.0,189.0,38.0,28.0,142.0,554.0,537.0,36.0,110.0,281.0,111.0,158.0,22.0,229.0,20.0,1065.0,57.0,194.0,34.0,747.0,155.0,24.0,326.0,739.0,14.0,29.0,55.0,101.0,572.0,148.0,179.0,22.0,81.0,188.0,243.0,153.0,144.0,323.0,402.0,264.0,414.0,261.0,23.0,75.0,13.0,50.0,159.0,42.0,10.0,179.0,420.0,79.0,622.0,68.0,90.0,73.0,70.0,128.0,221.0,20.0,120.0,294.0,166.0,292.0,542.0,76.0,22.0,32.0,388.0,195.0,930.0,107.0,43.0,256.0,381.0,268.0,301.0,75.0,128.0,271.0,333.0,247.0,131.0,112.0,388.0,37.0
BATTERY,405.0,39.0,137.0,105.0,373.0,1231.0,2490.0,185.0,294.0,743.0,142.0,74.0,245.0,408.0,79.0,60.0,242.0,983.0,1003.0,70.0,200.0,485.0,245.0,256.0,33.0,438.0,36.0,2115.0,107.0,399.0,55.0,1540.0,291.0,80.0,558.0,1307.0,43.0,27.0,116.0,197.0,1335.0,259.0,377.0,60.0,164.0,328.0,539.0,224.0,285.0,514.0,838.0,445.0,996.0,528.0,74.0,139.0,27.0,107.0,344.0,89.0,38.0,348.0,778.0,126.0,1371.0,151.0,154.0,212.0,138.0,236.0,460.0,32.0,182.0,703.0,273.0,723.0,1036.0,193.0,49.0,68.0,747.0,329.0,1759.0,277.0,90.0,404.0,768.0,443.0,565.0,170.0,252.0,519.0,588.0,575.0,265.0,209.0,748.0,118.0
BURGLARY,105.0,40.0,42.0,33.0,70.0,235.0,331.0,55.0,128.0,185.0,43.0,15.0,85.0,91.0,94.0,11.0,54.0,225.0,137.0,14.0,46.0,91.0,88.0,39.0,30.0,128.0,28.0,260.0,16.0,74.0,25.0,169.0,71.0,7.0,112.0,200.0,13.0,7.0,25.0,36.0,218.0,99.0,164.0,17.0,47.0,75.0,270.0,206.0,95.0,130.0,108.0,199.0,157.0,112.0,7.0,54.0,1.0,45.0,53.0,20.0,1.0,97.0,144.0,100.0,110.0,64.0,100.0,18.0,18.0,63.0,168.0,14.0,22.0,186.0,20.0,133.0,172.0,10.0,50.0,33.0,157.0,54.0,349.0,33.0,24.0,75.0,204.0,107.0,57.0,35.0,64.0,271.0,165.0,198.0,305.0,119.0,134.0,27.0
CONCEALED CARRY LICENSE VIOLATION,0.0,0.0,1.0,0.0,1.0,3.0,7.0,1.0,1.0,6.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,2.0,4.0,1.0,1.0,3.0,1.0,0.0,2.0,1.0,0.0,7.0,0.0,0.0,1.0,4.0,24.0,1.0,2.0,9.0,1.0,1.0,0.0,1.0,4.0,1.0,1.0,2.0,0.0,0.0,7.0,0.0,0.0,9.0,7.0,4.0,11.0,5.0,1.0,1.0,1.0,0.0,1.0,0.0,0.0,4.0,4.0,0.0,19.0,0.0,0.0,55.0,0.0,1.0,2.0,0.0,0.0,3.0,0.0,1.0,4.0,0.0,0.0,0.0,2.0,0.0,3.0,0.0,0.0,4.0,0.0,3.0,1.0,1.0,3.0,3.0,3.0,1.0,3.0,0.0,4.0,0.0
CRIMINAL DAMAGE,295.0,42.0,83.0,94.0,232.0,862.0,1145.0,153.0,216.0,410.0,110.0,30.0,214.0,246.0,179.0,35.0,213.0,615.0,525.0,49.0,137.0,334.0,162.0,215.0,47.0,189.0,29.0,1077.0,59.0,231.0,59.0,746.0,306.0,37.0,436.0,713.0,22.0,25.0,147.0,121.0,618.0,235.0,271.0,45.0,117.0,321.0,371.0,256.0,214.0,349.0,399.0,326.0,477.0,267.0,22.0,99.0,23.0,76.0,208.0,48.0,7.0,211.0,371.0,175.0,603.0,78.0,126.0,89.0,120.0,158.0,308.0,21.0,106.0,404.0,141.0,320.0,675.0,44.0,39.0,39.0,575.0,252.0,1028.0,105.0,49.0,219.0,382.0,365.0,309.0,103.0,169.0,502.0,462.0,345.0,453.0,134.0,423.0,52.0
CRIMINAL SEXUAL ASSAULT,12.0,0.0,6.0,3.0,13.0,43.0,95.0,6.0,5.0,24.0,5.0,2.0,7.0,12.0,2.0,2.0,16.0,25.0,47.0,7.0,6.0,19.0,3.0,0.0,3.0,23.0,0.0,60.0,3.0,9.0,3.0,57.0,7.0,9.0,21.0,42.0,3.0,0.0,2.0,7.0,45.0,25.0,11.0,4.0,4.0,8.0,52.0,15.0,12.0,39.0,24.0,28.0,37.0,19.0,4.0,7.0,0.0,2.0,9.0,1.0,0.0,14.0,21.0,9.0,46.0,4.0,4.0,2.0,1.0,13.0,15.0,1.0,8.0,44.0,4.0,32.0,35.0,7.0,1.0,6.0,16.0,5.0,53.0,72.0,8.0,14.0,44.0,17.0,16.0,1.0,6.0,34.0,15.0,25.0,9.0,11.0,26.0,3.0
CRIMINAL TRESPASS,63.0,11.0,11.0,8.0,38.0,109.0,172.0,20.0,41.0,71.0,29.0,10.0,52.0,52.0,21.0,2.0,18.0,102.0,83.0,17.0,22.0,63.0,38.0,23.0,3.0,77.0,13.0,143.0,12.0,26.0,7.0,97.0,49.0,16.0,51.0,110.0,6.0,16.0,19.0,10.0,124.0,46.0,50.0,2.0,35.0,26.0,106.0,63.0,59.0,62.0,72.0,68.0,310.0,71.0,34.0,21.0,11.0,12.0,29.0,14.0,11.0,77.0,64.0,35.0,89.0,20.0,62.0,85.0,10.0,47.0,65.0,12.0,20.0,188.0,14.0,127.0,95.0,37.0,12.0,9.0,60.0,25.0,135.0,75.0,21.0,62.0,108.0,54.0,36.0,17.0,32.0,175.0,53.0,72.0,57.0,43.0,101.0,35.0
DECEPTIVE PRACTICE,160.0,43.0,83.0,40.0,163.0,276.0,432.0,68.0,140.0,229.0,100.0,44.0,127.0,132.0,90.0,12.0,89.0,217.0,205.0,41.0,76.0,156.0,99.0,45.0,39.0,195.0,35.0,330.0,14.0,127.0,30.0,232.0,185.0,58.0,150.0,229.0,24.0,21.0,33.0,70.0,301.0,180.0,187.0,7.0,81.0,104.0,438.0,247.0,173.0,170.0,167.0,193.0,652.0,137.0,119.0,63.0,28.0,56.0,127.0,57.0,13.0,154.0,170.0,131.0,197.0,77.0,124.0,170.0,33.0,132.0,193.0,36.0,42.0,583.0,17.0,216.0,239.0,89.0,50.0,50.0,123.0,84.0,302.0,195.0,51.0,96.0,311.0,175.0,77.0,73.0,85.0,337.0,151.0,216.0,147.0,168.0,176.0,70.0
GAMBLING,0.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
HOMICIDE,2.0,1.0,2.0,2.0,2.0,18.0,44.0,2.0,3.0,3.0,1.0,0.0,3.0,3.0,1.0,1.0,4.0,8.0,6.0,0.0,1.0,4.0,0.0,6.0,0.0,2.0,0.0,18.0,3.0,3.0,1.0,24.0,1.0,0.0,3.0,22.0,0.0,0.0,2.0,0.0,17.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,7.0,13.0,1.0,5.0,2.0,0.0,1.0,0.0,0.0,6.0,0.0,0.0,4.0,6.0,1.0,21.0,0.0,1.0,2.0,0.0,1.0,3.0,0.0,0.0,9.0,8.0,3.0,18.0,0.0,0.0,1.0,9.0,5.0,21.0,2.0,0.0,6.0,2.0,3.0,5.0,0.0,2.0,6.0,6.0,3.0,1.0,2.0,6.0,0.0
HUMAN TRAFFICKING,0.0,0.0,1.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
INTERFERENCE WITH PUBLIC OFFICER,5.0,0.0,6.0,0.0,4.0,23.0,40.0,4.0,2.0,21.0,0.0,0.0,2.0,3.0,0.0,2.0,4.0,28.0,26.0,8.0,1.0,10.0,0.0,3.0,0.0,1.0,1.0,77.0,6.0,7.0,1.0,34.0,6.0,1.0,9.0,40.0,3.0,0.0,0.0,2.0,43.0,3.0,7.0,4.0,3.0,3.0,3.0,0.0,2.0,5.0,16.0,5.0,88.0,4.0,1.0,3.0,1.0,1.0,7.0,0.0,4.0,15.0,12.0,2.0,28.0,0.0,2.0,0.0,2.0,3.0,15.0,1.0,11.0,12.0,4.0,5.0,61.0,1.0,0.0,0.0,14.0,2.0,19.0,2.0,1.0,7.0,2.0,11.0,15.0,4.0,6.0,10.0,34.0,5.0,3.0,5.0,5.0,0.0
INTIMIDATION,0.0,0.0,0.0,1.0,0.0,3.0,4.0,0.0,0.0,1.0,0.0,0.0,4.0,3.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,2.0,0.0,1.0,5.0,0.0,4.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,3.0,0.0,0.0,0.0,0.0,4.0,1.0,3.0,0.0,0.0,2.0,5.0,2.0,0.0,2.0,1.0,4.0,5.0,5.0,1.0,0.0,0.0,2.0,2.0,0.0,0.0,2.0,2.0,0.0,3.0,0.0,2.0,1.0,0.0,0.0,2.0,0.0,1.0,5.0,0.0,11.0,1.0,1.0,1.0,0.0,0.0,1.0,3.0,1.0,0.0,2.0,1.0,1.0,1.0,0.0,0.0,2.0,2.0,8.0,3.0,1.0,1.0,0.0
KIDNAPPING,0.0,0.0,0.0,0.0,0.0,4.0,4.0,0.0,1.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,6.0,0.0,2.0,0.0,3.0,0.0,0.0,0.0,1.0,0.0,4.0,1.0,1.0,3.0,0.0,0.0,1.0,0.0,1.0,3.0,0.0,0.0,0.0,3.0,0.0,2.0,0.0,0.0,1.0,0.0,0.0,3.0,2.0,0.0,2.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0,1.0,0.0,1.0,3.0,0.0,4.0,1.0,0.0,0.0,1.0,1.0,2.0,1.0,1.0,1.0,2.0,0.0,1.0,0.0,1.0,2.0,3.0,1.0,0.0,0.0,2.0,0.0
LIQUOR LAW VIOLATION,0.0,0.0,1.0,1.0,1.0,3.0,7.0,0.0,1.0,11.0,2.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,1.0,2.0,0.0,5.0,2.0,1.0,0.0,1.0,4.0,0.0,5.0,1.0,0.0,2.0,0.0,0.0,3.0,3.0,0.0,0.0,6.0,4.0,0.0,2.0,2.0,1.0,0.0,4.0,4.0,0.0,0.0,5.0,7.0,11.0,3.0,0.0,1.0,1.0,3.0,1.0,2.0,1.0,1.0,2.0,1.0,4.0,2.0,1.0,2.0,0.0,1.0,6.0,0.0,0.0,5.0,0.0,4.0,0.0,1.0,0.0,1.0,3.0,1.0,1.0,0.0,1.0,1.0,0.0,1.0,3.0,0.0,1.0,15.0,0.0,4.0,3.0,5.0,2.0,3.0
MOTOR VEHICLE THEFT,151.0,22.0,74.0,49.0,223.0,555.0,762.0,97.0,120.0,277.0,69.0,17.0,120.0,117.0,62.0,26.0,187.0,403.0,276.0,29.0,87.0,346.0,112.0,200.0,35.0,123.0,7.0,632.0,59.0,137.0,40.0,445.0,140.0,26.0,425.0,410.0,14.0,16.0,101.0,65.0,479.0,186.0,146.0,23.0,53.0,189.0,242.0,159.0,95.0,308.0,173.0,220.0,353.0,181.0,7.0,55.0,3.0,60.0,97.0,25.0,10.0,219.0,224.0,80.0,310.0,59.0,59.0,78.0,115.0,72.0,203.0,17.0,62.0,197.0,81.0,216.0,460.0,28.0,28.0,18.0,366.0,190.0,625.0,86.0,60.0,179.0,184.0,291.0,245.0,70.0,155.0,348.0,278.0,241.0,315.0,155.0,284.0,17.0
NARCOTICS,28.0,0.0,14.0,9.0,8.0,109.0,834.0,10.0,22.0,72.0,9.0,0.0,16.0,15.0,8.0,3.0,13.0,58.0,191.0,8.0,8.0,45.0,15.0,14.0,1.0,16.0,0.0,405.0,18.0,25.0,6.0,976.0,45.0,3.0,54.0,144.0,5.0,2.0,1.0,11.0,1134.0,5.0,24.0,10.0,19.0,16.0,31.0,9.0,24.0,35.0,144.0,25.0,250.0,24.0,2.0,9.0,0.0,1.0,28.0,0.0,18.0,56.0,61.0,18.0,994.0,15.0,13.0,14.0,4.0,15.0,75.0,5.0,10.0,73.0,5.0,83.0,126.0,6.0,10.0,4.0,55.0,26.0,113.0,8.0,2.0,41.0,48.0,57.0,47.0,8.0,13.0,77.0,60.0,20.0,19.0,13.0,59.0,2.0
NON-CRIMINAL,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
OBSCENITY,0.0,1.0,0.0,0.0,1.0,1.0,3.0,0.0,0.0,2.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,2.0,0.0,1.0,3.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,2.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,2.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,1.0,3.0,2.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0,0.0,0.0,0.0,0.0,1.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0
OFFENSE INVOLVING CHILDREN,13.0,1.0,2.0,1.0,26.0,55.0,51.0,9.0,3.0,29.0,9.0,1.0,9.0,28.0,0.0,5.0,12.0,36.0,28.0,2.0,13.0,11.0,14.0,14.0,0.0,7.0,1.0,95.0,7.0,23.0,1.0,58.0,15.0,0.0,27.0,55.0,1.0,0.0,8.0,10.0,58.0,18.0,8.0,0.0,4.0,21.0,5.0,1.0,9.0,16.0,27.0,18.0,6.0,14.0,1.0,2.0,0.0,6.0,23.0,3.0,0.0,11.0,31.0,6.0,38.0,11.0,6.0,1.0,5.0,6.0,17.0,0.0,9.0,12.0,14.0,20.0,57.0,3.0,4.0,1.0,30.0,28.0,69.0,6.0,3.0,17.0,14.0,17.0,17.0,6.0,17.0,10.0,32.0,19.0,9.0,7.0,31.0,0.0
OTHER NARCOTIC VIOLATION,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
OTHER OFFENSE,217.0,19.0,85.0,28.0,169.0,510.0,841.0,73.0,121.0,330.0,79.0,14.0,112.0,172.0,38.0,27.0,72.0,443.0,457.0,9.0,103.0,179.0,170.0,123.0,18.0,170.0,16.0,815.0,44.0,172.0,31.0,425.0,151.0,14.0,230.0,443.0,20.0,9.0,59.0,97.0,452.0,103.0,248.0,14.0,70.0,137.0,183.0,89.0,113.0,196.0,375.0,204.0,319.0,134.0,15.0,65.0,9.0,52.0,170.0,49.0,9.0,173.0,252.0,71.0,531.0,75.0,88.0,102.0,42.0,71.0,277.0,14.0,102.0,204.0,102.0,231.0,507.0,37.0,30.0,19.0,303.0,121.0,575.0,78.0,21.0,121.0,182.0,250.0,190.0,88.0,131.0,167.0,312.0,239.0,89.0,85.0,245.0,21.0
PROSTITUTION,13.0,0.0,0.0,1.0,0.0,0.0,46.0,0.0,1.0,5.0,0.0,0.0,1.0,3.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,5.0,0.0,0.0,0.0,8.0,70.0,0.0,4.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,2.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,2.0,0.0,3.0,0.0,0.0,0.0,0.0,1.0,2.0,0.0,0.0,0.0,0.0,0.0,5.0,0.0,1.0,0.0,0.0,0.0,3.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
PUBLIC INDECENCY,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0
PUBLIC PEACE VIOLATION,7.0,3.0,4.0,3.0,7.0,23.0,31.0,1.0,0.0,8.0,1.0,1.0,8.0,4.0,2.0,1.0,2.0,12.0,14.0,5.0,5.0,15.0,4.0,7.0,0.0,6.0,2.0,37.0,4.0,6.0,1.0,43.0,10.0,6.0,16.0,21.0,13.0,2.0,0.0,6.0,33.0,4.0,5.0,0.0,3.0,5.0,17.0,9.0,3.0,13.0,41.0,9.0,80.0,24.0,3.0,2.0,5.0,0.0,5.0,2.0,10.0,24.0,7.0,7.0,44.0,2.0,6.0,73.0,3.0,7.0,7.0,6.0,3.0,40.0,2.0,5.0,18.0,6.0,0.0,2.0,5.0,4.0,16.0,19.0,1.0,9.0,8.0,19.0,12.0,1.0,5.0,28.0,4.0,6.0,8.0,8.0,6.0,5.0
ROBBERY,48.0,2.0,23.0,33.0,34.0,162.0,338.0,29.0,39.0,89.0,14.0,15.0,26.0,37.0,30.0,10.0,25.0,162.0,122.0,34.0,11.0,57.0,14.0,19.0,10.0,57.0,0.0,287.0,38.0,56.0,1.0,269.0,34.0,12.0,66.0,210.0,8.0,4.0,13.0,27.0,191.0,48.0,36.0,9.0,16.0,32.0,112.0,46.0,28.0,55.0,127.0,79.0,218.0,63.0,11.0,19.0,6.0,6.0,37.0,6.0,4.0,36.0,103.0,17.0,174.0,18.0,9.0,2.0,12.0,27.0,39.0,8.0,9.0,152.0,32.0,82.0,157.0,33.0,3.0,9.0,105.0,57.0,222.0,17.0,21.0,63.0,81.0,63.0,38.0,23.0,31.0,95.0,68.0,66.0,77.0,50.0,76.0,26.0
SEX OFFENSE,17.0,0.0,4.0,2.0,16.0,17.0,60.0,6.0,9.0,23.0,6.0,2.0,9.0,8.0,7.0,3.0,9.0,16.0,31.0,3.0,7.0,13.0,9.0,4.0,1.0,18.0,1.0,44.0,1.0,13.0,2.0,29.0,9.0,1.0,10.0,19.0,2.0,0.0,4.0,7.0,46.0,12.0,16.0,1.0,7.0,7.0,34.0,15.0,24.0,14.0,27.0,28.0,52.0,24.0,3.0,3.0,0.0,2.0,13.0,4.0,0.0,19.0,17.0,6.0,25.0,4.0,5.0,7.0,3.0,11.0,24.0,2.0,3.0,27.0,2.0,28.0,31.0,6.0,4.0,3.0,13.0,5.0,30.0,8.0,3.0,12.0,37.0,14.0,3.0,4.0,13.0,24.0,18.0,23.0,11.0,9.0,20.0,2.0
STALKING,5.0,0.0,2.0,2.0,7.0,16.0,22.0,2.0,1.0,11.0,3.0,0.0,2.0,1.0,7.0,1.0,5.0,3.0,15.0,0.0,2.0,4.0,6.0,1.0,0.0,7.0,0.0,17.0,2.0,4.0,0.0,22.0,6.0,2.0,12.0,8.0,2.0,4.0,4.0,2.0,10.0,9.0,4.0,1.0,6.0,4.0,6.0,6.0,7.0,9.0,8.0,7.0,12.0,3.0,1.0,2.0,0.0,0.0,0.0,3.0,0.0,3.0,5.0,6.0,16.0,3.0,8.0,3.0,1.0,3.0,12.0,0.0,8.0,15.0,0.0,13.0,6.0,3.0,1.0,0.0,3.0,3.0,30.0,3.0,3.0,4.0,9.0,9.0,12.0,0.0,5.0,21.0,13.0,5.0,2.0,6.0,8.0,1.0
THEFT,452.0,160.0,398.0,105.0,293.0,867.0,1829.0,153.0,724.0,925.0,241.0,199.0,407.0,392.0,536.0,51.0,238.0,1075.0,697.0,164.0,174.0,643.0,252.0,193.0,151.0,776.0,39.0,1207.0,101.0,567.0,80.0,797.0,359.0,253.0,585.0,839.0,82.0,140.0,142.0,151.0,1052.0,980.0,500.0,59.0,143.0,496.0,1919.0,1267.0,702.0,721.0,632.0,1074.0,2797.0,533.0,570.0,273.0,123.0,146.0,427.0,90.0,33.0,471.0,543.0,343.0,691.0,299.0,261.0,502.0,146.0,432.0,775.0,259.0,250.0,2543.0,123.0,910.0,826.0,360.0,90.0,143.0,448.0,371.0,1274.0,638.0,285.0,381.0,1328.0,444.0,344.0,139.0,463.0,1734.0,449.0,638.0,905.0,716.0,698.0,189.0
WEAPONS VIOLATION,36.0,3.0,20.0,15.0,40.0,135.0,308.0,20.0,21.0,74.0,9.0,1.0,23.0,50.0,5.0,8.0,38.0,115.0,163.0,16.0,8.0,76.0,10.0,43.0,1.0,17.0,0.0,432.0,35.0,72.0,6.0,261.0,39.0,8.0,107.0,259.0,17.0,1.0,13.0,34.0,176.0,16.0,21.0,27.0,7.0,29.0,29.0,18.0,15.0,52.0,136.0,35.0,89.0,40.0,8.0,19.0,5.0,6.0,44.0,3.0,26.0,47.0,123.0,8.0,253.0,13.0,3.0,32.0,34.0,15.0,68.0,5.0,21.0,89.0,38.0,34.0,147.0,12.0,3.0,2.0,122.0,45.0,246.0,20.0,5.0,62.0,33.0,93.0,81.0,21.0,32.0,27.0,82.0,24.0,13.0,18.0,124.0,2.0

In [14]:
aggregate.loc[2025].loc[['ROBBERY', 'HOMICIDE']]

primary_neighborhood,Albany Park,Andersonville,Archer Heights,Armour Square,Ashburn,Auburn Gresham,Austin,Avalon Park,Avondale,Belmont Cragin,Beverly,Boystown,Bridgeport,Brighton Park,Bucktown,Burnside,Calumet Heights,Chatham,Chicago Lawn,Chinatown,Clearing,Douglas,Dunning,East Side,East Village,Edgewater,Edison Park,Englewood,Fuller Park,Gage Park,Galewood,Garfield Park,Garfield Ridge,Gold Coast,Grand Boulevard,Grand Crossing,Grant Park,Greektown,Hegewisch,Hermosa,Humboldt Park,Hyde Park,Irving Park,Jackson Park,Jefferson Park,Kenwood,Lake View,Lincoln Park,Lincoln Square,"Little Italy, UIC",Little Village,Logan Square,Loop,Lower West Side,Magnificent Mile,Mckinley Park,Millenium Park,Montclare,Morgan Park,Mount Greenwood,Museum Campus,Near South Side,New City,North Center,North Lawndale,North Park,Norwood Park,O'Hare,Oakland,Old Town,Portage Park,Printers Row,Pullman,River North,Riverdale,Rogers Park,Roseland,Rush & Division,"Sauganash,Forest Glen",Sheffield & DePaul,South Chicago,South Deering,South Shore,Streeterville,Ukrainian Village,United Center,Uptown,Washington Heights,Washington Park,West Elsdon,West Lawn,West Loop,West Pullman,West Ridge,West Town,Wicker Park,Woodlawn,Wrigleyville
primary_type,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
ROBBERY,48.0,2.0,23.0,33.0,34.0,162.0,338.0,29.0,39.0,89.0,14.0,15.0,26.0,37.0,30.0,10.0,25.0,162.0,122.0,34.0,11.0,57.0,14.0,19.0,10.0,57.0,0.0,287.0,38.0,56.0,1.0,269.0,34.0,12.0,66.0,210.0,8.0,4.0,13.0,27.0,191.0,48.0,36.0,9.0,16.0,32.0,112.0,46.0,28.0,55.0,127.0,79.0,218.0,63.0,11.0,19.0,6.0,6.0,37.0,6.0,4.0,36.0,103.0,17.0,174.0,18.0,9.0,2.0,12.0,27.0,39.0,8.0,9.0,152.0,32.0,82.0,157.0,33.0,3.0,9.0,105.0,57.0,222.0,17.0,21.0,63.0,81.0,63.0,38.0,23.0,31.0,95.0,68.0,66.0,77.0,50.0,76.0,26.0
HOMICIDE,2.0,1.0,2.0,2.0,2.0,18.0,44.0,2.0,3.0,3.0,1.0,0.0,3.0,3.0,1.0,1.0,4.0,8.0,6.0,0.0,1.0,4.0,0.0,6.0,0.0,2.0,0.0,18.0,3.0,3.0,1.0,24.0,1.0,0.0,3.0,22.0,0.0,0.0,2.0,0.0,17.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,7.0,13.0,1.0,5.0,2.0,0.0,1.0,0.0,0.0,6.0,0.0,0.0,4.0,6.0,1.0,21.0,0.0,1.0,2.0,0.0,1.0,3.0,0.0,0.0,9.0,8.0,3.0,18.0,0.0,0.0,1.0,9.0,5.0,21.0,2.0,0.0,6.0,2.0,3.0,5.0,0.0,2.0,6.0,6.0,3.0,1.0,2.0,6.0,0.0

In [15]:
aggregate.loc[
    [(2024, 'ROBBERY'), (2024, 'HOMICIDE'),
     (2025, 'ROBBERY'), (2025, 'HOMICIDE')]
]

primary_neighborhood  Albany Park  Andersonville  Archer Heights  \
year primary_type
2024 ROBBERY                 72.0            2.0            38.0
     HOMICIDE                 5.0            0.0             0.0
2025 ROBBERY                 48.0            2.0            23.0
     HOMICIDE                 2.0            1.0             2.0

primary_neighborhood  Armour Square  Ashburn  Auburn Gresham  Austin  \
year primary_type
2024 ROBBERY                   38.0     49.0           231.0   610.0
     HOMICIDE                   1.0      5.0            30.0    48.0
2025 ROBBERY                   33.0     34.0           162.0   338.0
     HOMICIDE                   2.0      2.0            18.0    44.0

primary_neighborhood  Avalon Park  Avondale  Belmont Cragin  Beverly  \
year primary_type
2024 ROBBERY                 32.0      74.0           165.0     18.0
     HOMICIDE                 2.0       0.0             4.0      1.0
2025 ROBBERY                 29.0      39.0            89.0     14.0
     HOMICIDE                 2.0       3.0             3.0      1.0

primary_neighborhood  Boystown  Bridgeport  Brighton Park  Bucktown  Burnside  \
year primary_type
2024 ROBBERY              12.0        47.0           82.0      39.0      15.0
     HOMICIDE              0.0         3.0            5.0       0.0       0.0
2025 ROBBERY              15.0        26.0           37.0      30.0      10.0
     HOMICIDE              0.0         3.0            3.0       1.0       1.0

primary_neighborhood  Calumet Heights  Chatham  Chicago Lawn  Chinatown  \
year primary_type
2024 ROBBERY                     50.0    266.0         193.0       56.0
     HOMICIDE                     5.0     25.0           8.0        4.0
2025 ROBBERY                     25.0    162.0         122.0       34.0
     HOMICIDE                     4.0      8.0           6.0        0.0

primary_neighborhood  Clearing  Douglas  Dunning  East Side  East Village  \
year primary_type
2024 ROBBERY              19.0     76.0     20.0       22.0          25.0
     HOMICIDE              0.0      9.0      1.0        3.0           0.0
2025 ROBBERY              11.0     57.0     14.0       19.0          10.0
     HOMICIDE              1.0      4.0      0.0        6.0           0.0

primary_neighborhood  Edgewater  Edison Park  Englewood  Fuller Park  \
year primary_type
2024 ROBBERY               93.0          3.0      447.0         44.0
     HOMICIDE               2.0          0.0       38.0          3.0
2025 ROBBERY               57.0          0.0      287.0         38.0
     HOMICIDE               2.0          0.0       18.0          3.0

primary_neighborhood  Gage Park  Galewood  Garfield Park  Garfield Ridge  \
year primary_type
2024 ROBBERY              128.0       8.0          363.0            44.0
     HOMICIDE              12.0       0.0           34.0             3.0
2025 ROBBERY               56.0       1.0          269.0            34.0
     HOMICIDE               3.0       1.0           24.0             1.0

primary_neighborhood  Gold Coast  Grand Boulevard  Grand Crossing  Grant Park  \
year primary_type
2024 ROBBERY                23.0             83.0           272.0        12.0
     HOMICIDE                1.0              7.0            34.0         0.0
2025 ROBBERY                12.0             66.0           210.0         8.0
     HOMICIDE                0.0              3.0            22.0         0.0

primary_neighborhood  Greektown  Hegewisch  Hermosa  Humboldt Park  Hyde Park  \
year primary_type
2024 ROBBERY               21.0       11.0     73.0          396.0       82.0
     HOMICIDE               0.0        0.0      2.0           18.0        2.0
2025 ROBBERY                4.0       13.0     27.0          191.0       48.0
     HOMICIDE               0.0        2.0      0.0           17.0        0.0

primary_neighborhood  Irving Park  Jackson Park  Jefferson Park  Kenwood  \
year primary_type
2024 ROBBERY                 85.0          12.0            16.0     61.0
     HOMICIDE                 2.0           1.0             2.0      2.0
2025 ROBBERY                 36.0           9.0            16.0     32.0
     HOMICIDE                 1.0           1.0             0.0      0.0

primary_neighborhood  Lake View  Lincoln Park  Lincoln Square  \
year primary_type
2024 ROBBERY              158.0          75.0            54.0
     HOMICIDE               2.0           1.0             1.0
2025 ROBBERY              112.0          46.0            28.0
     HOMICIDE               0.0           0.0             1.0

primary_neighborhood  Little Italy, UIC  Little Village  Logan Square   Loop  \
year primary_type
2024 ROBBERY                      113.0           248.0         144.0  275.0
     HOMICIDE                       7.0            24.0           3.0    3.0
2025 ROBBERY                       55.0           127.0          79.0  218.0
     HOMICIDE                       7.0            13.0           1.0    5.0

primary_neighborhood  Lower West Side  Magnificent Mile  Mckinley Park  \
year primary_type
2024 ROBBERY                    112.0              15.0           47.0
     HOMICIDE                     8.0               0.0            2.0
2025 ROBBERY                     63.0              11.0           19.0
     HOMICIDE                     2.0               0.0            1.0

primary_neighborhood  Millenium Park  Montclare  Morgan Park  Mount Greenwood  \
year primary_type
2024 ROBBERY                    12.0       14.0         46.0              4.0
     HOMICIDE                    0.0        0.0          2.0              0.0
2025 ROBBERY                     6.0        6.0         37.0              6.0
     HOMICIDE                    0.0        0.0          6.0              0.0

primary_neighborhood  Museum Campus  Near South Side  New City  North Center  \
year primary_type
2024 ROBBERY                    5.0             62.0     236.0          38.0
     HOMICIDE                   0.0              5.0      15.0           0.0
2025 ROBBERY                    4.0             36.0     103.0          17.0
     HOMICIDE                   0.0              4.0       6.0           1.0

primary_neighborhood  North Lawndale  North Park  Norwood Park  O'Hare  \
year primary_type
2024 ROBBERY                   305.0        20.0          16.0     7.0
     HOMICIDE                   28.0         0.0           0.0     0.0
2025 ROBBERY                   174.0        18.0           9.0     2.0
     HOMICIDE                   21.0         0.0           1.0     2.0

primary_neighborhood  Oakland  Old Town  Portage Park  Printers Row  Pullman  \
year primary_type
2024 ROBBERY             22.0      60.0          82.0          16.0     16.0
     HOMICIDE             2.0       0.0           1.0           0.0      4.0
2025 ROBBERY             12.0      27.0          39.0           8.0      9.0
     HOMICIDE             0.0       1.0           3.0           0.0      0.0

primary_neighborhood  River North  Riverdale  Rogers Park  Roseland  \
year primary_type
2024 ROBBERY                188.0       28.0        108.0     176.0
     HOMICIDE                 3.0        1.0          7.0      21.0
2025 ROBBERY                152.0       32.0         82.0     157.0
     HOMICIDE                 9.0        8.0          3.0      18.0

primary_neighborhood  Rush & Division  Sauganash,Forest Glen  \
year primary_type
2024 ROBBERY                     52.0                    7.0
     HOMICIDE                     0.0                    0.0
2025 ROBBERY                     33.0                    3.0
     HOMICIDE                     0.0                    0.0

primary_neighborhood  Sheffield & DePaul  South Chicago  South Deering  \
year primary_type
2024 ROBBERY                        17.0          138.0           47.0
     HOMICIDE                        0.0           14.0            3.0
2025 ROBBERY                         9.0          105.0           57.0
     HOMICIDE                        1.0            9.0            5.0

primary_neighborhood  South Shore  Streeterville  Ukrainian Village  \
year primary_type
2024 ROBBERY                315.0           39.0               27.0
     HOMICIDE                36.0            2.0                0.0
2025 ROBBERY                222.0           17.0               21.0
     HOMICIDE                21.0            2.0                0.0

primary_neighborhood  United Center  Uptown  Washington Heights  \
year primary_type
2024 ROBBERY                  111.0   120.0                69.0
     HOMICIDE                   6.0     2.0                 8.0
2025 ROBBERY                   63.0    81.0                63.0
     HOMICIDE                   6.0     2.0                 3.0

primary_neighborhood  Washington Park  West Elsdon  West Lawn  West Loop  \
year primary_type
2024 ROBBERY                     61.0         47.0       43.0      173.0
     HOMICIDE                    10.0          1.0        0.0        3.0
2025 ROBBERY                     38.0         23.0       31.0       95.0
     HOMICIDE                     5.0          0.0        2.0        6.0

primary_neighborhood  West Pullman  West Ridge  West Town  Wicker Park  \
year primary_type
2024 ROBBERY                 107.0       119.0      129.0         83.0
     HOMICIDE                 19.0         4.0        2.0          0.0
2025 ROBBERY                  68.0        66.0       77.0         50.0
     HOMICIDE                  6.0         3.0        1.0          2.0

primary_neighborhood  Woodlawn  Wrigleyville
year primary_type
2024 ROBBERY             113.0          28.0
     HOMICIDE             12.0           0.0
2025 ROBBERY              76.0          26.0
     HOMICIDE              6.0           0.0

In [16]:
aggregate.loc[(slice(2024, 2025), ['ROBBERY', 'HOMICIDE']), :]

primary_neighborhood  Albany Park  Andersonville  Archer Heights  \
year primary_type
2024 HOMICIDE                 5.0            0.0             0.0
     ROBBERY                 72.0            2.0            38.0
2025 HOMICIDE                 2.0            1.0             2.0
     ROBBERY                 48.0            2.0            23.0

primary_neighborhood  Armour Square  Ashburn  Auburn Gresham  Austin  \
year primary_type
2024 HOMICIDE                   1.0      5.0            30.0    48.0
     ROBBERY                   38.0     49.0           231.0   610.0
2025 HOMICIDE                   2.0      2.0            18.0    44.0
     ROBBERY                   33.0     34.0           162.0   338.0

primary_neighborhood  Avalon Park  Avondale  Belmont Cragin  Beverly  \
year primary_type
2024 HOMICIDE                 2.0       0.0             4.0      1.0
     ROBBERY                 32.0      74.0           165.0     18.0
2025 HOMICIDE                 2.0       3.0             3.0      1.0
     ROBBERY                 29.0      39.0            89.0     14.0

primary_neighborhood  Boystown  Bridgeport  Brighton Park  Bucktown  Burnside  \
year primary_type
2024 HOMICIDE              0.0         3.0            5.0       0.0       0.0
     ROBBERY              12.0        47.0           82.0      39.0      15.0
2025 HOMICIDE              0.0         3.0            3.0       1.0       1.0
     ROBBERY              15.0        26.0           37.0      30.0      10.0

primary_neighborhood  Calumet Heights  Chatham  Chicago Lawn  Chinatown  \
year primary_type
2024 HOMICIDE                     5.0     25.0           8.0        4.0
     ROBBERY                     50.0    266.0         193.0       56.0
2025 HOMICIDE                     4.0      8.0           6.0        0.0
     ROBBERY                     25.0    162.0         122.0       34.0

primary_neighborhood  Clearing  Douglas  Dunning  East Side  East Village  \
year primary_type
2024 HOMICIDE              0.0      9.0      1.0        3.0           0.0
     ROBBERY              19.0     76.0     20.0       22.0          25.0
2025 HOMICIDE              1.0      4.0      0.0        6.0           0.0
     ROBBERY              11.0     57.0     14.0       19.0          10.0

primary_neighborhood  Edgewater  Edison Park  Englewood  Fuller Park  \
year primary_type
2024 HOMICIDE               2.0          0.0       38.0          3.0
     ROBBERY               93.0          3.0      447.0         44.0
2025 HOMICIDE               2.0          0.0       18.0          3.0
     ROBBERY               57.0          0.0      287.0         38.0

primary_neighborhood  Gage Park  Galewood  Garfield Park  Garfield Ridge  \
year primary_type
2024 HOMICIDE              12.0       0.0           34.0             3.0
     ROBBERY              128.0       8.0          363.0            44.0
2025 HOMICIDE               3.0       1.0           24.0             1.0
     ROBBERY               56.0       1.0          269.0            34.0

primary_neighborhood  Gold Coast  Grand Boulevard  Grand Crossing  Grant Park  \
year primary_type
2024 HOMICIDE                1.0              7.0            34.0         0.0
     ROBBERY                23.0             83.0           272.0        12.0
2025 HOMICIDE                0.0              3.0            22.0         0.0
     ROBBERY                12.0             66.0           210.0         8.0

primary_neighborhood  Greektown  Hegewisch  Hermosa  Humboldt Park  Hyde Park  \
year primary_type
2024 HOMICIDE               0.0        0.0      2.0           18.0        2.0
     ROBBERY               21.0       11.0     73.0          396.0       82.0
2025 HOMICIDE               0.0        2.0      0.0           17.0        0.0
     ROBBERY                4.0       13.0     27.0          191.0       48.0

primary_neighborhood  Irving Park  Jackson Park  Jefferson Park  Kenwood  \
year primary_type
2024 HOMICIDE                 2.0           1.0             2.0      2.0
     ROBBERY                 85.0          12.0            16.0     61.0
2025 HOMICIDE                 1.0           1.0             0.0      0.0
     ROBBERY                 36.0           9.0            16.0     32.0

primary_neighborhood  Lake View  Lincoln Park  Lincoln Square  \
year primary_type
2024 HOMICIDE               2.0           1.0             1.0
     ROBBERY              158.0          75.0            54.0
2025 HOMICIDE               0.0           0.0             1.0
     ROBBERY              112.0          46.0            28.0

primary_neighborhood  Little Italy, UIC  Little Village  Logan Square   Loop  \
year primary_type
2024 HOMICIDE                       7.0            24.0           3.0    3.0
     ROBBERY                      113.0           248.0         144.0  275.0
2025 HOMICIDE                       7.0            13.0           1.0    5.0
     ROBBERY                       55.0           127.0          79.0  218.0

primary_neighborhood  Lower West Side  Magnificent Mile  Mckinley Park  \
year primary_type
2024 HOMICIDE                     8.0               0.0            2.0
     ROBBERY                    112.0              15.0           47.0
2025 HOMICIDE                     2.0               0.0            1.0
     ROBBERY                     63.0              11.0           19.0

primary_neighborhood  Millenium Park  Montclare  Morgan Park  Mount Greenwood  \
year primary_type
2024 HOMICIDE                    0.0        0.0          2.0              0.0
     ROBBERY                    12.0       14.0         46.0              4.0
2025 HOMICIDE                    0.0        0.0          6.0              0.0
     ROBBERY                     6.0        6.0         37.0              6.0

primary_neighborhood  Museum Campus  Near South Side  New City  North Center  \
year primary_type
2024 HOMICIDE                   0.0              5.0      15.0           0.0
     ROBBERY                    5.0             62.0     236.0          38.0
2025 HOMICIDE                   0.0              4.0       6.0           1.0
     ROBBERY                    4.0             36.0     103.0          17.0

primary_neighborhood  North Lawndale  North Park  Norwood Park  O'Hare  \
year primary_type
2024 HOMICIDE                   28.0         0.0           0.0     0.0
     ROBBERY                   305.0        20.0          16.0     7.0
2025 HOMICIDE                   21.0         0.0           1.0     2.0
     ROBBERY                   174.0        18.0           9.0     2.0

primary_neighborhood  Oakland  Old Town  Portage Park  Printers Row  Pullman  \
year primary_type
2024 HOMICIDE             2.0       0.0           1.0           0.0      4.0
     ROBBERY             22.0      60.0          82.0          16.0     16.0
2025 HOMICIDE             0.0       1.0           3.0           0.0      0.0
     ROBBERY             12.0      27.0          39.0           8.0      9.0

primary_neighborhood  River North  Riverdale  Rogers Park  Roseland  \
year primary_type
2024 HOMICIDE                 3.0        1.0          7.0      21.0
     ROBBERY                188.0       28.0        108.0     176.0
2025 HOMICIDE                 9.0        8.0          3.0      18.0
     ROBBERY                152.0       32.0         82.0     157.0

primary_neighborhood  Rush & Division  Sauganash,Forest Glen  \
year primary_type
2024 HOMICIDE                     0.0                    0.0
     ROBBERY                     52.0                    7.0
2025 HOMICIDE                     0.0                    0.0
     ROBBERY                     33.0                    3.0

primary_neighborhood  Sheffield & DePaul  South Chicago  South Deering  \
year primary_type
2024 HOMICIDE                        0.0           14.0            3.0
     ROBBERY                        17.0          138.0           47.0
2025 HOMICIDE                        1.0            9.0            5.0
     ROBBERY                         9.0          105.0           57.0

primary_neighborhood  South Shore  Streeterville  Ukrainian Village  \
year primary_type
2024 HOMICIDE                36.0            2.0                0.0
     ROBBERY                315.0           39.0               27.0
2025 HOMICIDE                21.0            2.0                0.0
     ROBBERY                222.0           17.0               21.0

primary_neighborhood  United Center  Uptown  Washington Heights  \
year primary_type
2024 HOMICIDE                   6.0     2.0                 8.0
     ROBBERY                  111.0   120.0                69.0
2025 HOMICIDE                   6.0     2.0                 3.0
     ROBBERY                   63.0    81.0                63.0

primary_neighborhood  Washington Park  West Elsdon  West Lawn  West Loop  \
year primary_type
2024 HOMICIDE                    10.0          1.0        0.0        3.0
     ROBBERY                     61.0         47.0       43.0      173.0
2025 HOMICIDE                     5.0          0.0        2.0        6.0
     ROBBERY                     38.0         23.0       31.0       95.0

primary_neighborhood  West Pullman  West Ridge  West Town  Wicker Park  \
year primary_type
2024 HOMICIDE                 19.0         4.0        2.0          0.0
     ROBBERY                 107.0       119.0      129.0         83.0
2025 HOMICIDE                  6.0         3.0        1.0          2.0
     ROBBERY                  68.0        66.0       77.0         50.0

primary_neighborhood  Woodlawn  Wrigleyville
year primary_type
2024 HOMICIDE             12.0           0.0
     ROBBERY             113.0          28.0
2025 HOMICIDE              6.0           0.0
     ROBBERY              76.0          26.0

In [17]:
reset_agg = aggregate.reset_index()
reset_agg.head()

primary_neighborhood,year,primary_type,Albany Park,Andersonville,Archer Heights,Armour Square,Ashburn,Auburn Gresham,Austin,Avalon Park,Avondale,Belmont Cragin,Beverly,Boystown,Bridgeport,Brighton Park,Bucktown,Burnside,Calumet Heights,Chatham,Chicago Lawn,Chinatown,Clearing,Douglas,Dunning,East Side,East Village,Edgewater,Edison Park,Englewood,Fuller Park,Gage Park,Galewood,Garfield Park,Garfield Ridge,Gold Coast,Grand Boulevard,Grand Crossing,Grant Park,Greektown,Hegewisch,Hermosa,Humboldt Park,Hyde Park,Irving Park,Jackson Park,Jefferson Park,Kenwood,Lake View,Lincoln Park,Lincoln Square,"Little Italy, UIC",Little Village,Logan Square,Loop,Lower West Side,Magnificent Mile,Mckinley Park,Millenium Park,Montclare,Morgan Park,Mount Greenwood,Museum Campus,Near South Side,New City,North Center,North Lawndale,North Park,Norwood Park,O'Hare,Oakland,Old Town,Portage Park,Printers Row,Pullman,River North,Riverdale,Rogers Park,Roseland,Rush & Division,"Sauganash,Forest Glen",Sheffield & DePaul,South Chicago,South Deering,South Shore,Streeterville,Ukrainian Village,United Center,Uptown,Washington Heights,Washington Park,West Elsdon,West Lawn,West Loop,West Pullman,West Ridge,West Town,Wicker Park,Woodlawn,Wrigleyville
0,2001,ARSON,12.0,1.0,3.0,4.0,8.0,14.0,72.0,3.0,18.0,27.0,1.0,1.0,20.0,15.0,4.0,7.0,6.0,18.0,29.0,0.0,9.0,6.0,4.0,6.0,4.0,10.0,1.0,73.0,2.0,12.0,1.0,29.0,7.0,0.0,10.0,22.0,0.0,0.0,4.0,23.0,43.0,3.0,17.0,0.0,2.0,4.0,7.0,1.0,5.0,8.0,37.0,24.0,0.0,23.0,0.0,7.0,0.0,5.0,7.0,3.0,0.0,3.0,40.0,9.0,30.0,1.0,1.0,1.0,2.0,1.0,11.0,0.0,2.0,7.0,4.0,13.0,37.0,0.0,1.0,3.0,14.0,9.0,15.0,0.0,2.0,2.0,13.0,8.0,12.0,5.0,11.0,1.0,17.0,8.0,14.0,7.0,18.0,0.0
1,2001,ASSAULT,232.0,35.0,76.0,55.0,276.0,879.0,1695.0,167.0,280.0,565.0,116.0,23.0,185.0,258.0,112.0,59.0,197.0,567.0,667.0,32.0,106.0,509.0,167.0,182.0,63.0,304.0,25.0,2159.0,106.0,235.0,67.0,892.0,265.0,29.0,702.0,855.0,4.0,20.0,64.0,220.0,1375.0,170.0,273.0,25.0,124.0,207.0,308.0,196.0,239.0,325.0,521.0,706.0,377.0,456.0,49.0,133.0,2.0,87.0,269.0,81.0,7.0,200.0,735.0,211.0,844.0,76.0,115.0,117.0,144.0,146.0,326.0,18.0,173.0,408.0,262.0,526.0,1035.0,77.0,35.0,37.0,720.0,216.0,1158.0,70.0,79.0,318.0,546.0,390.0,428.0,71.0,156.0,155.0,624.0,274.0,259.0,273.0,633.0,21.0
2,2001,BATTERY,802.0,76.0,222.0,210.0,674.0,2796.0,5594.0,430.0,754.0,1379.0,212.0,71.0,546.0,757.0,216.0,165.0,426.0,1585.0,2155.0,67.0,260.0,1765.0,419.0,466.0,162.0,865.0,66.0,7130.0,333.0,668.0,153.0,3127.0,619.0,158.0,2667.0,2718.0,31.0,58.0,195.0,592.0,3977.0,424.0,990.0,64.0,265.0,554.0,845.0,498.0,622.0,998.0,1715.0,1790.0,684.0,1095.0,76.0,304.0,5.0,196.0,653.0,170.0,39.0,686.0,2396.0,501.0,2971.0,182.0,284.0,291.0,392.0,352.0,842.0,47.0,380.0,1644.0,888.0,1647.0,2922.0,261.0,85.0,118.0,2009.0,596.0,3354.0,187.0,235.0,1095.0,1637.0,934.0,1580.0,199.0,450.0,308.0,1753.0,776.0,731.0,717.0,1923.0,115.0
3,2001,BURGLARY,245.0,59.0,119.0,58.0,249.0,811.0,936.0,122.0,420.0,669.0,138.0,26.0,331.0,397.0,275.0,26.0,161.0,529.0,826.0,33.0,154.0,177.0,204.0,145.0,132.0,284.0,33.0,1380.0,70.0,342.0,111.0,517.0,293.0,23.0,364.0,568.0,3.0,7.0,54.0,218.0,861.0,165.0,389.0,29.0,131.0,132.0,612.0,369.0,264.0,204.0,580.0,672.0,202.0,263.0,26.0,217.0,1.0,85.0,213.0,56.0,4.0,71.0,619.0,332.0,437.0,93.0,138.0,44.0,50.0,128.0,455.0,14.0,80.0,299.0,106.0,382.0,606.0,37.0,79.0,92.0,359.0,136.0,776.0,61.0,165.0,131.0,261.0,257.0,212.0,156.0,207.0,146.0,485.0,334.0,395.0,440.0,329.0,47.0
4,2001,CRIM SEXUAL ASSAULT,18.0,0.0,4.0,3.0,12.0,51.0,136.0,5.0,14.0,19.0,3.0,0.0,5.0,10.0,9.0,7.0,9.0,38.0,50.0,1.0,5.0,35.0,8.0,4.0,1.0,22.0,1.0,134.0,3.0,9.0,4.0,60.0,12.0,2.0,45.0,47.0,0.0,1.0,4.0,16.0,54.0,13.0,22.0,4.0,6.0,11.0,15.0,11.0,9.0,20.0,28.0,33.0,12.0,12.0,0.0,4.0,0.0,2.0,7.0,1.0,1.0,11.0,44.0,6.0,50.0,5.0,2.0,3.0,4.0,9.0,10.0,0.0,10.0,20.0,13.0,26.0,56.0,5.0,4.0,6.0,43.0,11.0,66.0,3.0,4.0,13.0,28.0,16.0,40.0,4.0,5.0,10.0,35.0,25.0,13.0,26.0,39.0,1.0

## New Data Set

In [18]:
reset_agg.primary_type.unique()

<ArrowExtensionArray>
[                            'ARSON',                           'ASSAULT',
                           'BATTERY',                          'BURGLARY',
               'CRIM SEXUAL ASSAULT',                   'CRIMINAL DAMAGE',
           'CRIMINAL SEXUAL ASSAULT',                 'CRIMINAL TRESPASS',
                'DECEPTIVE PRACTICE',                 'DOMESTIC VIOLENCE',
                          'GAMBLING',                          'HOMICIDE',
  'INTERFERENCE WITH PUBLIC OFFICER',                      'INTIMIDATION',
                        'KIDNAPPING',              'LIQUOR LAW VIOLATION',
               'MOTOR VEHICLE THEFT',                         'NARCOTICS',
                         'OBSCENITY',        'OFFENSE INVOLVING CHILDREN',
          'OTHER NARCOTIC VIOLATION',                     'OTHER OFFENSE',
                      'PROSTITUTION',                  'PUBLIC INDECENCY',
            'PUBLIC PEACE VIOLATION',                         'RITUALISM',
                           'ROBBERY',                       'SEX OFFENSE',
                          'STALKING',                             'THEFT',
                 'WEAPONS VIOLATION',                 'HUMAN TRAFFICKING',
 'CONCEALED CARRY LICENSE VIOLATION',                      'NON-CRIMINAL']
Length: 34, dtype: string[pyarrow]

In [19]:
# rearrange data
neighborhood_cols = reset_agg.columns[2:]   # all neighborhood columns

df_long = reset_agg.melt(
    id_vars=['year', 'primary_type'],
    value_vars=neighborhood_cols,
    var_name='neighborhood',
    value_name='crime_count'
)
df_long.head()

   year         primary_type neighborhood  crime_count
0  2001                ARSON  Albany Park         12.0
1  2001              ASSAULT  Albany Park        232.0
2  2001              BATTERY  Albany Park        802.0
3  2001             BURGLARY  Albany Park        245.0
4  2001  CRIM SEXUAL ASSAULT  Albany Park         18.0

#### Calculating the Z-score highlights specialized anomalies—places where a specific crime type is occurring at a rate far beyond what is statistically normal for the rest of the city.
- A Z-score above 3.0 is typically considered a significant outlier; seeing scores of 5.0 to 8.0 indicates extreme geographic concentration.

In [20]:
# Calculate mean and standard deviation per year/type
stats = df_long.groupby(['year', 'primary_type'], observed=False)['crime_count'].agg(['mean', 'std']).fillna(0)

# Merge back and calculate Z-Score
df_long = df_long.merge(stats, on=['year', 'primary_type'])
df_long['z_score'] = (df_long['crime_count'] - df_long['mean']) / df_long['std']

# Find the most "Extreme" statistical outliers
extremes = df_long[df_long['year'] == 2025].sort_values('z_score', ascending=False)

In [21]:
extremes[['neighborhood', 'primary_type', 'crime_count', 'z_score']].head(10)

,neighborhood,primary_type,crime_count,z_score
51993,O'Hare,CONCEALED CARRY LICENSE VIOLATION,55.0,8.090589
25237,Garfield Ridge,PROSTITUTION,70.0,7.993028
40535,Loop,OTHER NARCOTIC VIOLATION,3.0,6.926511
5334,Austin,HOMICIDE,44.0,5.831036
40538,Loop,PUBLIC INDECENCY,2.0,5.641306
40532,Loop,NON-CRIMINAL,1.0,5.598530
58127,Rogers Park,NON-CRIMINAL,1.0,5.598530
31352,Humboldt Park,NON-CRIMINAL,1.0,5.598530
31351,Humboldt Park,NARCOTICS,1134.0,5.349758
40521,Loop,CRIMINAL TRESPASS,310.0,5.290609

In [22]:
extremes.describe(include='all').T

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
year,3038.0,<NA>,<NA>,<NA>,2025.0,0.0,2025.0,2025.0,2025.0,2025.0,2025.0
primary_type,3038,31,CONCEALED CARRY LICENSE VIOLATION,98,NaN,NaN,NaN,NaN,NaN,NaN,NaN
neighborhood,3038,98,O'Hare,31,NaN,NaN,NaN,NaN,NaN,NaN,NaN
crime_count,3038.0,NaN,NaN,NaN,75.725477,196.943123,0.0,0.0,5.0,54.75,2797.0
mean,3038.0,NaN,NaN,NaN,75.725477,128.932724,0.030612,1.387755,10.612245,96.285714,544.744898
std,3038.0,NaN,NaN,NaN,78.936518,127.115714,0.17315,1.875686,13.949565,114.01786,501.627913
z_score,3038.0,NaN,NaN,NaN,0.0,0.995049,-1.182882,-0.593138,-0.303296,0.144527,8.090589

### Descriptive & EDA

In [ ]:
crime_year =

In [26]:
# take a look at 2024 & 2025
df_2025 = df_long.iloc[:, :4][df_long.year ==2025].reset_index(drop=True)
df_2024 = df_long.iloc[:, :4][df_long.year ==2024].reset_index(drop=True)

In [27]:
df_2025.head()

   year                       primary_type neighborhood  crime_count
0  2025                              ARSON  Albany Park          2.0
1  2025                            ASSAULT  Albany Park        203.0
2  2025                            BATTERY  Albany Park        405.0
3  2025                           BURGLARY  Albany Park        105.0
4  2025  CONCEALED CARRY LICENSE VIOLATION  Albany Park          0.0

In [31]:
df_2025.year.unique(), df_2024.year.unique()

(<ArrowExtensionArray>
 [2025]
 Length: 1, dtype: int64[pyarrow],
 <ArrowExtensionArray>
 [2024]
 Length: 1, dtype: int64[pyarrow])

## 2025 ANOVA

In [36]:
# Normality test on the 'crime_count' column
normality_results = pg.normality(df_2025['crime_count'])

print("--- Normality Test Results ---")
print(normality_results)

--- Normality Test Results ---
                    W          pval  normal
crime_count  0.417191  1.241935e-71   False

- The data is extremely non-normal, and test homoscedasticity.

In [61]:
# Testing if variance in 'crime_count' is equal across different primary_type & neighborhood
homogeneity_p_results = pg.homoscedasticity(data=df_2025, dv='crime_count', group='primary_type')
homogeneity_n_results = pg.homoscedasticity(data=df_2025, dv='crime_count', group='neighborhood')


print("\n--- Homogeneity of Variance Results ---\n")
print("Homogeneity result for Type of Crime:\n", homogeneity_p_results.to_string())
print("\nHomogeneity result for Neighborhood:\n", homogeneity_n_results.to_string())

--- Homogeneity of Variance Results ---

Homogeneity result for Type of Crime:
                 W           pval  equal_var
levene  48.977947  1.036113e-233      False

Homogeneity result for Neighborhood:
                W          pval  equal_var
levene  4.161421  7.892982e-36      False

In [64]:
# Use Welch's ANOVA instead of regular ANOVA
welch_res_2025_p = pg.welch_anova(data=df_2025, dv='crime_count', between='primary_type')
welch_res_2025_n = pg.welch_anova(data=df_2025, dv='crime_count', between='neighborhood')
print(welch_res_2025_p.to_string())
print("\n", welch_res_2025_n.to_string())

         Source  ddof1       ddof2          F          p-unc       np2
0  primary_type     30  1058.13242  61.907701  4.669137e-209  0.428593

          Source  ddof1       ddof2         F         p-unc      np2
0  neighborhood     97  999.592027  4.573427  9.077035e-36  0.12136

(3038, 4)

- This is partial eta‑squared (np2), an effect size.
    - 0.01 = small
    - 0.06 = medium
    - 0.14 = large
    - 0.43 = extremely large

- Interpretation:
    - About 43% of all variance in crime_count is explained by crime type.
    - That is a huge effect.

In [45]:
# Testing if variance in 'crime_count' is equal across different 'neighborhood'
homogeneity_results = pg.homoscedasticity(data=df_2025, dv='crime_count', group='neighborhood')

print("\n--- Homogeneity of Variance Results ---")
print(homogeneity_results)

--- Homogeneity of Variance Results ---
               W          pval  equal_var
levene  4.161421  7.892982e-36      False

In [44]:
# Use Welch's ANOVA instead of regular ANOVA
welch_res_2025 = pg.welch_anova(data=df_2025, dv='crime_count', between='neighborhood')
welch_res_2025

         Source  ddof1       ddof2         F         p-unc      np2
0  neighborhood     97  999.592027  4.573427  9.077035e-36  0.12136

#### Conclusion
- Comparing Homoscedasticity and  for primary_type, which represents crime types, and neighborhood for 2025 reported crimes

In [25]:
# The "Robust" T-test approach:
robust_crime = pg.pairwise_tests(
    data=df_2024_2025, 
    dv='crime_count', 
    between='neighborhood', 
    parametric=True, 
    correction=True # This handles the unequal variance (Welch's)
)

In [26]:
robust_crime.info()
robust_crime.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4753 entries, 0 to 4752
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Contrast     4753 non-null   object
 1   A            4753 non-null   object
 2   B            4753 non-null   object
 3   Paired       4753 non-null   bool
 4   Parametric   4753 non-null   bool
 5   T            4753 non-null   float64
 6   dof          4753 non-null   float64
 7   alternative  4753 non-null   object
 8   p-unc        4753 non-null   float64
 9   BF10         4753 non-null   object
 10  hedges       4753 non-null   float64
dtypes: bool(2), float64(4), object(5)
memory usage: 343.6+ KB

,Contrast,A,B,Paired,Parametric,T,dof,alternative,p-unc,BF10,hedges
0,neighborhood,Albany Park,Andersonville,False,True,3.589389,68.846894,two-sided,0.000616,54.39,0.640702
1,neighborhood,Albany Park,Archer Heights,False,True,2.093167,94.884359,two-sided,0.039002,1.367,0.373628
2,neighborhood,Albany Park,Armour Square,False,True,3.299155,67.791680,two-sided,0.001548,23.24,0.588896
3,neighborhood,Albany Park,Ashburn,False,True,0.280644,119.816446,two-sided,0.779468,0.199,0.050095
4,neighborhood,Albany Park,Auburn Gresham,False,True,-2.768333,79.753337,two-sided,0.007003,5.787,-0.494144

In [29]:
# The "Robust" T-test approach with :
robust_crime_bonf = pg.pairwise_tests(
    data=df_2024_2025, 
    dv='crime_count', 
    between='neighborhood', 
    parametric=True, 
    correction=True, # This handles the unequal variance (Welch's)
    padjust='bonf'   # Bonferroni correction
)
#  statistical method to prevent false positives (Type I errors) 
# when performing multiple hypothesis tests by adjusting the significance level, 
# making it harder to declare results significant

In [30]:
robust_crime_bonf.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4753 entries, 0 to 4752
Data columns (total 13 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Contrast     4753 non-null   object
 1   A            4753 non-null   object
 2   B            4753 non-null   object
 3   Paired       4753 non-null   bool
 4   Parametric   4753 non-null   bool
 5   T            4753 non-null   float64
 6   dof          4753 non-null   float64
 7   alternative  4753 non-null   object
 8   p-unc        4753 non-null   float64
 9   p-corr       4753 non-null   float64
 10  p-adjust     4753 non-null   object
 11  BF10         4753 non-null   object
 12  hedges       4753 non-null   float64
dtypes: bool(2), float64(5), object(6)
memory usage: 417.9+ KB

In [36]:

robust_crime_bonf.BF10 = robust_crime_bonf.BF10.astype('float')
robust_crime_bonf.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4753 entries, 0 to 4752
Data columns (total 13 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Contrast     4753 non-null   object
 1   A            4753 non-null   object
 2   B            4753 non-null   object
 3   Paired       4753 non-null   bool
 4   Parametric   4753 non-null   bool
 5   T            4753 non-null   float64
 6   dof          4753 non-null   float64
 7   alternative  4753 non-null   object
 8   p-unc        4753 non-null   float64
 9   p-corr       4753 non-null   float64
 10  p-adjust     4753 non-null   object
 11  BF10         4753 non-null   object
 12  hedges       4753 non-null   float64
dtypes: bool(2), float64(5), object(6)
memory usage: 417.9+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4753 entries, 0 to 4752
Data columns (total 13 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Contrast     4753 non-null   object
 1   A            4753 non-null   object
 2   B            4753 non-null   object
 3   Paired       4753 non-null   bool
 4   Parametric   4753 non-null   bool
 5   T            4753 non-null   float64
 6   dof          4753 non-null   float64
 7   alternative  4753 non-null   object
 8   p-unc        4753 non-null   float64
 9   p-corr       4753 non-null   float64
 10  p-adjust     4753 non-null   object
 11  BF10         4753 non-null   float64
 12  hedges       4753 non-null   float64
dtypes: bool(2), float64(6), object(5)
memory usage: 417.9+ KB

In [27]:
robust_crime.info()
robust_crime.BF10 = robust_crime.BF10.astype('float')
robust_crime.sort_values(by='BF10', ascending=False).head(10)

NameError: name 'robust_crime' is not defined

,Contrast,A,B,Paired,Parametric,T,dof,alternative,p-unc,BF10,hedges
3119,neighborhood,Humboldt Park,Museum Campus,False,True,4.866078,61.101534,two-sided,0.000008,4539.429,0.868590
2210,neighborhood,Edison Park,Humboldt Park,False,True,-4.837865,61.180189,two-sided,0.000009,4071.489,-0.863554
3115,neighborhood,Humboldt Park,Millenium Park,False,True,4.802582,61.570375,two-sided,0.000010,3555.859,0.857256
2865,neighborhood,Grant Park,Humboldt Park,False,True,-4.802491,61.310188,two-sided,0.000010,3554.624,-0.857239
1374,neighborhood,Burnside,Humboldt Park,False,True,-4.791841,61.207266,two-sided,0.000011,3412.755,-0.855338
3102,neighborhood,Humboldt Park,Jackson Park,False,True,4.778456,61.293646,two-sided,0.000011,3242.751,0.852949
2925,neighborhood,Greektown,Humboldt Park,False,True,-4.777810,61.476421,two-sided,0.000011,3234.774,-0.852834
2570,neighborhood,Garfield Park,Museum Campus,False,True,4.731846,61.105649,two-sided,0.000014,2716.409,0.844629
135,neighborhood,Andersonville,Humboldt Park,False,True,-4.719979,61.917833,two-sided,0.000014,2597.169,-0.842511
2067,neighborhood,East Village,Humboldt Park,False,True,-4.711790,61.719743,two-sided,0.000014,2518.081,-0.841049

In [37]:
robust_crime_bonf.BF10 = robust_crime_bonf.BF10.astype('float')
robust_crime_bonf.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4753 entries, 0 to 4752
Data columns (total 13 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Contrast     4753 non-null   object
 1   A            4753 non-null   object
 2   B            4753 non-null   object
 3   Paired       4753 non-null   bool
 4   Parametric   4753 non-null   bool
 5   T            4753 non-null   float64
 6   dof          4753 non-null   float64
 7   alternative  4753 non-null   object
 8   p-unc        4753 non-null   float64
 9   p-corr       4753 non-null   float64
 10  p-adjust     4753 non-null   object
 11  BF10         4753 non-null   float64
 12  hedges       4753 non-null   float64
dtypes: bool(2), float64(6), object(5)
memory usage: 417.9+ KB

In [38]:
robust_crime_bonf.sort_values(by='BF10', ascending=False).head(10)

,Contrast,A,B,Paired,Parametric,T,dof,alternative,p-unc,p-corr,p-adjust,BF10,hedges
3119,neighborhood,Humboldt Park,Museum Campus,False,True,4.866078,61.101534,two-sided,0.000008,0.039736,bonf,4539.429,0.868590
2210,neighborhood,Edison Park,Humboldt Park,False,True,-4.837865,61.180189,two-sided,0.000009,0.043940,bonf,4071.489,-0.863554
3115,neighborhood,Humboldt Park,Millenium Park,False,True,4.802582,61.570375,two-sided,0.000010,0.049456,bonf,3555.859,0.857256
2865,neighborhood,Grant Park,Humboldt Park,False,True,-4.802491,61.310188,two-sided,0.000010,0.049796,bonf,3554.624,-0.857239
1374,neighborhood,Burnside,Humboldt Park,False,True,-4.791841,61.207266,two-sided,0.000011,0.051889,bonf,3412.755,-0.855338
3102,neighborhood,Humboldt Park,Jackson Park,False,True,4.778456,61.293646,two-sided,0.000011,0.054348,bonf,3242.751,0.852949
2925,neighborhood,Greektown,Humboldt Park,False,True,-4.777810,61.476421,two-sided,0.000011,0.054230,bonf,3234.774,-0.852834
2570,neighborhood,Garfield Park,Museum Campus,False,True,4.731846,61.105649,two-sided,0.000014,0.064606,bonf,2716.409,0.844629
135,neighborhood,Andersonville,Humboldt Park,False,True,-4.719979,61.917833,two-sided,0.000014,0.066140,bonf,2597.169,-0.842511
2067,neighborhood,East Village,Humboldt Park,False,True,-4.711790,61.719743,two-sided,0.000014,0.068441,bonf,2518.081,-0.841049

In [31]:
# This tests Year, Neighborhood, primary_type
model = ols('crime_count ~ C(year) + C(neighborhood) + C(primary_type)', data=df_long).fit()
anova_results = anova_lm(model, typ=2)

In [32]:
anova_results

                       sum_sq       df            F         PR(>F)
C(year)          7.683053e+07     24.0    54.782289  1.993514e-260
C(neighborhood)  9.980606e+08     97.0   176.077068   0.000000e+00
C(primary_type)  2.427117e+09     33.0  1258.619424   0.000000e+00
Residual         4.371909e+09  74815.0          NaN            NaN

In [33]:
print(anova_results)

                       sum_sq       df            F         PR(>F)
C(year)          7.683053e+07     24.0    54.782289  1.993514e-260
C(neighborhood)  9.980606e+08     97.0   176.077068   0.000000e+00
C(primary_type)  2.427117e+09     33.0  1258.619424   0.000000e+00
Residual         4.371909e+09  74815.0          NaN            NaN

In [40]:
# largest crime
df_long_filtered['primary_type'].value_counts().nlargest(5).index

Index(['ARSON', 'ASSAULT', 'BATTERY', 'BURGLARY',
       'CONCEALED CARRY LICENSE VIOLATION'],
      dtype='string[pyarrow]', name='primary_type')

In [34]:
# largest crime
df_long_filtered['neighborhood'].value_counts().nlargest(5).index

Index(['Albany Park', 'Andersonville', 'Archer Heights', 'Armour Square',
       'Ashburn'],
      dtype='string[pyarrow]', name='neighborhood')

In [29]:
# Create a count table
counts = df_long_filtered.groupby(['neighborhood', 'primary_type']).size().unstack(fill_value=0)

# Find combinations with only 1 sample (Standard Deviation is impossible)
single_samples = (counts == 1).sum().sum()

# Find combinations with 0 samples (Mean/SD are NaN)
zero_samples = (counts == 0).sum().sum()

print(f"Groups with 1 sample: {single_samples}")
print(f"Groups with 0 samples: {zero_samples}")

Groups with 1 sample: 0
Groups with 0 samples: 0

In [33]:
# 1. Filter out pairs that couldn't be calculated (NaN)
# 2. Filter for significant results (p < 0.05)
significant_results = posthocs.dropna(subset=['p-unc'])
significant_results = significant_results[significant_results['p-unc'] < 0.05]

print(significant_results.head().to_string())

        Contrast neighborhood            A              B Paired Parametric         T   dof alternative     p-unc   BF10    hedges
0   neighborhood            -  Albany Park  Andersonville  False       True  2.413472  18.0   two-sided  0.026678  2.592  1.033732
10  neighborhood            -  Albany Park       Boystown  False       True  2.219374  18.0   two-sided  0.039549  1.986  0.950596
14  neighborhood            -  Albany Park       Burnside  False       True  2.337110  18.0   two-sided  0.031189   2.33  1.001025
18  neighborhood            -  Albany Park      Chinatown  False       True  2.226112  18.0   two-sided  0.039020  2.004  0.953482
23  neighborhood            -  Albany Park   East Village  False       True  2.429926  18.0   two-sided  0.025790  2.653  1.040779

In [44]:
import pathlib

# This gets the directory you are currently working in
current_dir = pathlib.Path.cwd()
# pathlib.Path.cwd()
# # To go two levels up, just like your original code intended:
# grandparent_dir = current_dir.parent.parent.absolute()
current_dir.parent.parent.absolute()

PosixPath('/Users/sir/Desktop/Project')

In [46]:
try:
    # Works in .py scripts
    root = pathlib.Path(__file__).parent.parent.absolute()
except NameError:
    # Works in Jupyter/Interactive shells
    root = pathlib.Path.cwd().parent.parent.absolute()

print(f"Project root is: {root}")

Project root is: /Users/sir/Desktop/Project

In [ ]:
# Fixed Two‑way ANOVA
aov_inter = pg.anova(
    data=df_long_filtered,
    dv='crime_count',
    between=['neighborhood', 'primary_type'],
    detailed=True
)

print(aov_inter)

In [23]:
# Two‑way ANOVA with interaction
aov_inter = pg.anova(
    data=df_long_filtered,
    dv='crime_count',
    between=['neighborhood', 'primary_type'],
    detailed=True
)

print(aov_inter.to_string())

                        Source            SS    DF            MS            F  p-unc       np2
0                 neighborhood  3.176246e+07    97  3.274481e+05   451.180134    0.0  0.935089
1                 primary_type  1.133591e+08    30  3.778637e+06  5206.462288    0.0  0.980921
2  neighborhood * primary_type  1.143131e+08  2910  3.928285e+04    54.126573    0.0  0.981077
3                     Residual  2.204856e+06  3038  7.257591e+02          NaN    NaN       NaN